### ISSUE TITLE
Graphical modeler collapses

### ISSUE THREAD

**Issue by Perzonallica** [FriendsOfTYPO3/extension_builder#106]
Hello,

when I click on the following buttons, the whole modeler collapses like this:

![image](https://user-images.githubusercontent.com/3707338/31219570-098edeb0-a9be-11e7-9fd3-97ed1f4830f2.png)

To continue to edit or work with the models, I have to manually change the height of the elements in firebug/dev tools. Opening an existing extension to the modeler doesn't help. I can reproduce this in Chrome & Firefox.

I'm using the latest version of the extension_builder on Typo3 8.7.7

**Comment by nicodh** [comment]
Do you see any Javascript errors in the console?

**Comment by Perzonallica** [comment]
No errors there.

**Comment by nicodh** [comment]
Can't reproduce this. Do you have gridelements installed? Sometimes people reported problems, when gridelements are installed together with the ExtensionBuilder...

**Comment by Perzonallica** [comment]
I'm really sorry, false alarm. This has nothing to do with extension_builder plugin. There was a problem with our CSS.
