### ISSUE TITLE
Extension could not be saved: Could not generate domain templates, error: template not found

### ISSUE THREAD

**Issue by mranguish** [FriendsOfTYPO3/extension_builder#109]
Hi, I'm using **typo3 cms 8.7.4** (production mode) with **extension builder 8.7.0**.
When I create a extension (or edit one) and add a custom action for example "archive", then I get the following error message:
> Extension could not be saved: Could not generate domain templates, error: template not found: Resources/Private/Templates/archive.htmlt

**Comment by derhecht** [comment]
For me TYPO3 8.7.8 with 8.7 extension-builder doesnt save at all and I got no error message :(
Even if a have no aggregate root nor custom function.
