### ISSUE TITLE
Graphical builder workspace misbehaviour

### ISSUE THREAD

**Issue by qbadev** [FriendsOfTYPO3/extension_builder#110]
When adding domain and giving it properties, it grows on screen. When organizing domains on screen, and going beyond workspace borders, it becomes impossible to see some domain interface controls, and even Builder controls as well. When drag&drop domain beyond top border, it becomes impossible to drag it again, as handler is out of workspace.

**Comment by nicodh** [comment]
Hmm, never had that issue so far, even if the screen is much smaller than the domain models.
Maybe you did some browser scaling?

**Comment by qbadev** [comment]
Using Linux Ubuntu 17.10 with Cinnamon Desktop. Trying this in Iron (chromium) and Google Chrome. Same issue in both browsers. When dragging domain down below the visible space, I can scroll to this domain, but cannot scroll back up enough to see i.e. "Expand left pane" button.
It seems that height of WireLayer or its parent is miscalculated or configured the wrong way (css + js), as when my issue happens, it looks like WireLayer buttons are just under Extension controls.
As You can see on the image, vertical scroll is stuck at the red line level I marked. Cannot scroll any more up. If this happens, I need to drag&drop upwards all domains that are too low.
![image](https://user-images.githubusercontent.com/293101/34413660-22de88b6-ebe5-11e7-9679-94bf425078f3.png)
When resizing my window in height, I also cannot scroll through left pane (there is no scrollbar at all).
Workspace does not resize when window resizes.
I will give it a try in FF, and also run my virtual Win 7 and see if it is wrong.

**Comment by qbadev** [comment]
same problem when using Win 7 with Google Chrome.

**Comment by qbadev** [comment]
maybe using this library would become useful for workspace panning
[https://github.com/anvaka/panzoom](https://github.com/anvaka/panzoom)

**Comment by qbadev** [comment]
it fixes only the inner height of designer workspace which lets one see all the form elements and controls, no elements are overflowing designer. 
Element with class _module-docheader t3js-module-docheader_ still covers top of designer when plenty of elements are inside

**Comment by qbadev** [comment]
In 9.5 version all works fine.
