### ISSUE TITLE
Not update ExtensionBuilder.json

### ISSUE THREAD

**Issue by CHDuBar** [FriendsOfTYPO3/extension_builder#112]
When I modify  the Model in Extension Builder Module at the moment of "Save Extension" generates the next error: 

> Call to undefined method EBT\ExtensionBuilder\Domain\Model\ClassObject\ClassObject::addFunction() 

The Domain, Controllers. Templates and other files update correctly but not the ExtensionBuilder.json, this file keeps its last version. So the porblem is if I want to do more changes I have to repeat the modifies, new model entitoes for example.
 
The screenshot of error is:
![2017-12-28 11_55_12-social media management system typo3 cms 7 6 23](https://user-images.githubusercontent.com/5651023/34417367-1cede66e-ebc6-11e7-851b-349f26d8f667.png)

**Comment by DavidBruchmann** [comment]
Did you try to remove the ExtensionBuilder.json after opening it in extension_builder?
