### ISSUE TITLE
Question: PHPDoc requires @throws

### ISSUE THREAD

**Issue by rowild** [FriendsOfTYPO3/extension_builder#122]
Hi,

this is just a question: phpstorm complains about a missing @throws tags in the PHPDoc comments in controller classes, where ever there is a addFlashMessage involved. 

My question:
1. Could extension_builder be told to generate them, too?
2. What would be the correct type to add after a @throws tag?

(Using the extension_builder 8.7 branch on a 8.7.10 installation.)

Thank you!

**Comment by liayn** [comment]
Hi Robert,

What is the exception phpstorm complains about?

**Comment by rowild** [comment]
Hi, Markus,

this is the complain:

![screen shot 2018-02-27 at 12 32 19](https://user-images.githubusercontent.com/213803/36726621-bc5b8624-1bba-11e8-8926-2a03fd6cbc58.png)

And actually, phpstorm offers an "Update" possibility, after which the code looks like this:

![screen shot 2018-02-27 at 12 32 37](https://user-images.githubusercontent.com/213803/36726668-e6564d56-1bba-11e8-872a-078b124c63bc.png)

Don't know how important that is... isn't your phpstorm complaining, as well, Markus?

**Comment by liayn** [comment]
The exceptions shown are all okay and expected. But they can't be put there generically. The `StopActionException` stems from a call to `redirect` i suppose. The second one I'm not sure and the last one should probably be caught inside the persistence layer or in your method, even though it is very unlikely that this exception ever pops up.

So I tend to say that extension_builder is not really a lot of help here, besides it could add those annotations for the dummy code generated, which would be an easy change.

**Comment by rowild** [comment]
I understand (partly). The @throws tags are quite different from action to action, of course.

One question: after adding the @throws manually in phpStrom, they will get overridden (that is: deleted) again, when I keep working with the extension_builder. Is there a way to tell the extension_builder to ignore them? (Just those lines, not the whole script?)

It's really just sugar on top and in my opinion not a must-have --- it is just a question.

Thanks again! G'day!

**Comment by liayn** [comment]
Hm.. I have no deeper knowledge in the PHP code generator library used here, So maybe @nicodh can answer this.

**Comment by nicodh** [comment]
At the moment all annotations are handled by the CodeGenerator - so maybe we should add some routine to keep existing annotations.
On the other hand I would not  agree to put all possibly thrown exceptions into each action method annotation. Especially the StopAction Exception is not a real "Exception".
I would suggest: 
1. always to keep existing annotations
2. add some throws annotations in standard actions like: create, update, delete etc.

**Comment by wmdbMattes** [comment]
That inspection is the first one I disable.
It is intended for shallow class designs (which extbase is definetely not).
The problem becomes worse once you run deep inspections which end up in a list of 20-30 throws annotations with no practical use.

I do understand the desire to get code „green“ in PHPStorm and I suffer from the same OCD, but do yourself a favour and disable that imspection :)

**Comment by liayn** [comment]
Just a note on that @wmdbMattes.

The basic idea is very clever actually: Clean programming means dealing with all error situations. That includes handling exceptions. So the decision is: catch it or throw it.
(Java *requires* you to do so too AFAIKs)

The problem we have here is that our beloved extbase doesn't cope with the exceptions at the lower levels "at all". Hence everything bubbles upwards causing all that annotation mess.

The StopException stuff is actually a bit different. I'm really not sure if I shouldn't even call it "failed by design". To my knowledge one shouldn't use exceptions for code flow control, but that's what this exception is purely there for, it does not even indicate any sort of problem.

**Comment by liayn** [comment]
Can we close this?

**Comment by rowild** [comment]
Yes. Thanks for the insights!
