### ISSUE TITLE
Can anyone record a video tutorial, such as using this tool to create a blog extension? 

### ISSUE THREAD

**Issue by jooler** [FriendsOfTYPO3/extension_builder#125]
Can anyone record a video tutorial, such as using this tool to create a blog extension? 
For people without programming basis, this tool is still too complex.

**Comment by nicodh** [comment]
This tool is not for people without programming knowledge. It's a tool to avoid writing boilerplate and to get an idea what the structure of a TYPO3 Extbase extensions looks like and how it works...
