### ISSUE TITLE
Grid will not show horizontal scroll bars if elements are outside the right border

### ISSUE THREAD

**Issue by taalas** [FriendsOfTYPO3/extension_builder#129]
Hi,

as already discussed in Slack, the current Extension Builder version will not show horizontal scroll bars if elements reach (or are outside) the right border. This used to work in 7.x. The bottom border scrolling behaviour is still working as expected though. Is there any chance that panning/zooming function could be added (as proposed in another issue)? The only way to currently reach objects outside the visible area for me is to manually hack the CSS to widen the viewport.

**Comment by taalas** [comment]
To follow up on this: I just recently discovered (while moving elements around) that there is indeed still a scroll bar at the bottom, it is just outside the visible area. When moving elements to the bottom of the canvas it is possible to scroll the complete inner element of the editor and reach the bottom scrollbar. This leads to the top parts now being covered by the to panel (all this without using the vertical scrollbar). It seems that the inner element's height is calculated incorrectly, thus making it to high to be completely visible. I can provide screenshots if needed.

**Comment by nicodh** [comment]
Can you please test if this fix solves the problem?

**Comment by taalas** [comment]
As per comment in the first commit it didn't solve the problem for me. The latest commit works perfectly though. Thanks for the fix!
