### ISSUE TITLE
Faults without model

### ISSUE THREAD

**Issue by DavidBruchmann** [FriendsOfTYPO3/extension_builder#142]
If the builder is used to make a more or less empty skeleton there are some faults:

- ext_icon.gif is missing
- in `ext_tables.php` a TypoScript-file is included but that file as well as the including folder `Configuration/TypoScript` are missing. As it's in many cases probably desired to include some TypoScript I'd propose to leave the content of `ext_tables.php` but to include the missing folder including the empty files `setup.txt` and `constants.txt`.

**Comment by liayn** [comment]
Would you mind re-checking your findings with the latest 9.10.3 release?

**Comment by simonschaufi** [comment]
no feedback.
