### ISSUE TITLE
Extension_buider with PHP 7.2

### ISSUE THREAD

**Issue by awelvor** [FriendsOfTYPO3/extension_builder#143]
Hi

I try to create a new extension,
I got the following message:

Extension could not be saved: PHP Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/mdn4/typo3conf/ext/extension_builder/Classes/Domain/Validator/ExtensionValidator.php line 524

I am using: PHP 7.2.5 with UBUNTU 18.04.1

It seems that default is due to PHP 7..2.5:

see: http://php.net/manual/fr/migration72.incompatible.php

Évolutions incompatibles avec les versions précédentes ¶
Empêcher number_format() de retourner zéro négatif ¶

**Comment by liayn** [comment]
Can you provide a pull request with a fix please?

**Comment by nicodh** [comment]
Can't reproduce this. All parrams passed to count calls in Validator should be arrays as far as I see...

**Comment by DeepDeeh** [comment]
This Error is because you are using Typo3 in DEBUG-Mode. Switch to Live and it works again.

**Comment by liayn** [comment]
@awelvor which version of extension builder do you use?

**Comment by liayn** [comment]
@nicodh I pushed a typehint fix for ExtensionValidator to master, which may be related here.

**Comment by DeepDeeh** [comment]
I use 8.7.0 with TYPO3 8.7.16
i just realised that actually setting BE/debug to 0 works, but i must logout and login after i set the parameter in installtool.

**Comment by liayn** [comment]
@DeepDeeh can you please try to use the latest version from git here please?
https://github.com/FriendsOfTYPO3/extension_builder/tree/8.7

**Comment by DeepDeeh** [comment]
I did. It works now, i can safe extensions when TYPO3 is in DEBUG mode. Thanks!

**Comment by liayn** [comment]
So we still wait for the version information from @awelvor

**Comment by r3h6** [comment]
This was fixed here: https://github.com/FriendsOfTYPO3/extension_builder/commits?author=r3h6

**Comment by pquerner** [comment]
Composer require still gives 0bae9c6f6db2b425bca3ff1d40a8371b18bda8ef

**Comment by nicodh** [comment]
Ok, I think this is because of missing tags. If you require 8.7.x-dev you will get the latest release in the 8.7 branch which includes all commits.
I will update the tags soon...

**Comment by pquerner** [comment]
Can confirm current 8.7 tree is working on 8.7.16. Thanks for the fast response.
