### ISSUE TITLE
PHP Warning: count(): Parameter must be an array or an object

### ISSUE THREAD

**Issue by simonschaufi** [FriendsOfTYPO3/extension_builder#149]
PHP Warning: count(): Parameter must be an array or an object that implements Countable in extension_builder/Classes/Domain/Validator/ExtensionValidator.php line 242

Extension Version: 8.7.0
PHP 7.2

I see the issue has been fixed but no new version has been released which is compatible with TYPO3 8.

**Comment by nicodh** [comment]
Did you investigate how this happened?
Plugins & BackendModules in Extension Model are initialized as arrays so I have no clue how this could happen...

**Comment by simonschaufi** [comment]
The issue has been fixed but no new version has been released which is compatible with TYPO3 8.

**Comment by liayn** [comment]
As @nicodh noted in some other tickets recently, he will not be able to do new TER releases soon. We generally recommend using the github version.

**Comment by simonschaufi** [comment]
Tagging a new version would totally be fine for me. I just need a new git tag.
