### ISSUE TITLE
Template error

### ISSUE THREAD

**Issue by gbanka** [FriendsOfTYPO3/extension_builder#150]
Error with select element: t3js-module-docheader-bar-navigation (Domain modeling)
![error](https://user-images.githubusercontent.com/2961401/44392003-7afa3a80-a531-11e8-8d48-3a2b659518c7.png)

**Comment by gbanka** [comment]
patch

**Comment by liayn** [comment]
Which TYPO3 version, which version of extension_builder (did you try latest GIT version here from github?)
