### ISSUE TITLE
Add support for Typo3 9

### ISSUE THREAD

**Issue by Req** [FriendsOfTYPO3/extension_builder#160]
Currently the latest supported version at https://extensions.typo3.org/extension/extension_builder/ is **7.6.18 / beta** -- is it possible to get support for Typo3 9.*?

Also, I use composer to get extension_builder - can I get the latest version somehow directly without using the extensions.typo3.org if that gives me support for newer versions?

**Comment by liayn** [comment]
Please always use the latest git version. With composer consider using dev-master for v9 or the other according branches, like https://github.com/FriendsOfTYPO3/extension_builder/tree/8.7
