### ISSUE TITLE
Can't resolve view

### ISSUE THREAD

**Issue by AncientChild** [FriendsOfTYPO3/extension_builder#172]
Currently, when creating a backend-module via extension-builder, typo3 seems unable to locate the template for that backend-module although the necessary files are existing. I guess there is a new way of setting the path for those files.

**Comment by nicodh** [comment]
Which version/branch did that happen?

**Comment by AncientChild** [comment]
I cloned the master branch today, and i am using TYPO3 version 9.4.0
I found a workaround, but by default the mentioned bug appears.

**Comment by nicodh** [comment]
If you found a workaround: can you provide a pull request?

**Comment by AncientChild** [comment]
The workaround lies in my own extension that i generated, i didn't change anything in the extension builder itself. Could you elaborate on your last comment? What exactly do you want me to do? Sorry, i am still a bit of a noob ;)

**Comment by nicodh** [comment]
I can't reproduce this. Can you investigate the typoscript configuration for the templates in Typoscript Objectbrowser...

**Comment by AncientChild** [comment]
Sorry for the late reply. Have been pretty busy in the meantime. I don't know what created the error for me. Right now i can't reproduce the error anymore- so yes, everything is working as it should now. This can be closed. Thanks.

**Comment by likunstk** [comment]
Sry to post here  i have the same problem on master with typo3 9.5.8. 
Sorry, the requested view was not found.

The technical reason is: No template was found. View could not be resolved for action "list" in class "Xyz\Xyxyxyxyzz\Controller\XXXyyyzzController".
