### ISSUE TITLE
Issue on saving new created extension

### ISSUE THREAD

**Issue by chnshure** [FriendsOfTYPO3/extension_builder#178]
Hi,
i'm getting this error if i want to save a new extension from scratch.

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Too few arguments to function EBT\ExtensionBuilder\Configuration\ExtensionBuilderConfigurationManager::getWiringEditorSmd(), 1 passed and exactly 2 expected | ArgumentCountError thrown in file .../typo3conf/ext/extension_builder/Classes/Configuration/ExtensionBuilderConfigurationManager.php in line 533. Requested URL: ..../typo3/index.php?route=%%2Fajax%%2FextensionBuilder%%2FwireEditor&token=--AnonymizedToken--`

Installed latest master of Extension Builder in a fresh TYPO3 9.5 instance. (Tried it with activated roundtrip and without).

**Comment by liayn** [comment]
I can't reproduce this issue.
(I used my existing latest master of the Core and latest master of EB)

I also see no reason (code wise) why `getWiringEditorSmd(ServerRequestInterface $request, ResponseInterface $response)` would be called without a response object. This is a normal ajax route via the Core. There is no explanation for this to me currently. Sorry.

**Comment by chnshure** [comment]
Thanks liayn. I doublechecked the server logs now and there was an 500 Error probably caused by .htaccess removed it and now it works. Sorry - my fault.
