### ISSUE TITLE
".ts" vs ".typoscript"?

### ISSUE THREAD

**Issue by martin-helmich** [FriendsOfTYPO3/extension_builder#189]
I noticed that TypoScript files are still [created with the `.ts` suffix](https://github.com/FriendsOfTYPO3/extension_builder/blob/master/Classes/Service/FileGenerator.php#L484) (which heavily collides with TypeScript and seriously confuses my editor), while the [new default/recommendation seems to be `.typoscript`](https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.7.x/Feature-78161-IntroduceTypoScriptFileExtension.html).

Any plans to change this or make this configurable? I'd be prepared to create a PR if so desired.

**Comment by liayn** [comment]
Of course the extension builder should stick to the recommendations of the Core. A PR is highly appreciated.

**Comment by martin-helmich** [comment]
Thanks for the quick response -- PR incoming (see #190). I've added some special logic to keep existing `.ts` files when existing extensions are edited with the Extension builder (seemed sensible to me -- entirely up for discussion, of course).
