### ISSUE TITLE
Save record in backend produces error: Unknown column 'l10n_state' in 'field list'

### ISSUE THREAD

**Issue by denweng** [FriendsOfTYPO3/extension_builder#19]
- Typo3 8.6.1
- extension_builder github clone from 1.3.

To reproduce:

- Create new extension with model
- install extension
- insert new record by list module

results in error:

```
Oops, an error occurred!
An exception occurred while executing 'SELECT `uid`, `l10n_state`, `sys_language_uid`, `l10n_parent` FROM `tx_test1_domain_model_test1` WHERE (`uid` IN (NULL)) AND ((`tx_test1_domain_model_test1`.`deleted` = 0) AND ((`tx_test1_domain_model_test1`.`t3ver_wsid` = 0) AND (`tx_test1_domain_model_test1`.`pid` <> -1)))': Unknown column 'l10n_state' in 'field list'
```

Any help welcome

**Comment by nicodh** [comment]
I think the reason is https://forge.typo3.org/issues/79658
That changeset introduced a new field which is not yet implemented in ExtensionBuilder
