### ISSUE TITLE
Error PhpParser TYPO3 9.5

### ISSUE THREAD

**Issue by NiklasLazinbee** [FriendsOfTYPO3/extension_builder#191]
I got an error message:

Return value of PhpParser\ParserFactory::create() must be an instance of PhpParser\Parser, instance of PhpParser\Parser\Php7 returned

in /var/www/web27486935/html/typo3_source/typo3_src-9.5.3/vendor/nikic/php-parser/lib/PhpParser/ParserFactory.php line 35

`return new Parser\Multiple([
		new Parser\Php5($lexer, $parserOptions), new Parser\Php7($lexer, $parserOptions)
	]);
case self::ONLY_PHP7:
	return new Parser\Php7($lexer, $parserOptions);
case self::ONLY_PHP5:
	return new Parser\Php5($lexer, $parserOptions);
default:`

at PhpParser\ParserFactory->create(3)
in /var/www/web27486935/html/ginkoo/typo3conf/ext/extension_builder/Classes/Service/ParserService.php line 57

`public function __construct() {
	$this->parser = (new ParserFactory)->create(ParserFactory::ONLY_PHP7);
}`

PHP version: 	7.2.13 
TYPO3 9.5.3

**Comment by nicodh** [comment]
Can't reproduce this. The strange thing is, that Parser\Php7 is an instance of PhpParser\Parser so there is nothing wrong with that...??
Did you find any possible reason?

**Comment by NiklasLazinbee** [comment]
So far i haven't found a reason. Maybe it has to do with my provider, I have to set the PHP version over the .htacces:
AddHandler x-httpd-php7.2 .php

**Comment by likunstk** [comment]
Do a clear all caches .. it will work then..
