### ISSUE TITLE
[BUGFIX] Use correct version number in composer.json

### ISSUE THREAD

**Issue by schams-net** [FriendsOfTYPO3/extension_builder#194]
When file `composer.json` file is generated during an extension creation, version `1.0.0` is added as a hard-coded value (see commit 19bfca85a07ec94c6fef774651a2789de8071ae8). 

I'd expect that the version number you enter as an extension property (under "More options") is used. This value is stored in file `ext_emconf.php` correctly, but not in `composer.json`.

**Comment by liayn** [comment]
composer,json should not have  version number at all, unless one really works without a CVS
