### ISSUE TITLE
Error when trying to use extension builder: Class EBT\ExtensionBuilder\Controller\BuilderModuleController does not exist. 

### ISSUE THREAD

**Issue by KyleGas** [FriendsOfTYPO3/extension_builder#195]
Hey there.

I am getting this error when trying to switch to the extension builder tab (after installing with composer): 

Class EBT\ExtensionBuilder\Controller\BuilderModuleController does not exist. 

the "more information regarding this error link" leads me here:

https://wiki.typo3.org/Exception/CMS/1278450972

But i don't know in what file i would make these changes?

Anybody know what to do? Thanks in advance!

**Comment by nicodh** [comment]
Maybe it helps if you run 
`composer dump-autoload`

**Comment by KyleGas** [comment]
Did that. Now what? Reupload the extension?

**Comment by nicodh** [comment]
Hmm, "reupload"?
Did you run that command on the server?
It should create an entry for ExtensionBuilder in vendor/composer/autoload_psr4.php

**Comment by KyleGas** [comment]
i don't know how to run composer on the server...

**Comment by KyleGas** [comment]
Is installing Typo3 without composer actually the better way? If so, how do i do it?

**Comment by nicodh** [comment]
Sorry this is not the place to ask general questions about installing TYPO3. Just look at the TYPO3 website for instructions please

**Comment by KyleGas** [comment]
alright. Is this the place to ask how to run composer on the server?

**Comment by nicodh** [comment]
No. It's the place to report bugs found in ExtensionBuilder...

**Comment by KyleGas** [comment]
OK, so you're gonna tell me a command but not where to run it... do you know where to find out how to run it on the server?

**Comment by nicodh** [comment]
Sorry - this is a voluntary based software project. I can't spend my time coaching people for free...

**Comment by KyleGas** [comment]
Sure, i understand. So i ran the command, found the file  autoload_psr4.php, replaced it on the server via FTP (since this is how i do things in typo3, cos i wouldnt know how to run composer on the server)
still same result.

**Comment by juergenweb** [comment]
Same problem here!

My settings:
TYPO3 9.5.18
PHP Version 7.4.5
MySQL 7.4.5
Extension Builder 9.10.2

I have installed the extension via composer and got the following message:
![Screenshot](https://user-images.githubusercontent.com/9609925/82829297-40b28f80-9eb3-11ea-9856-232a1f1de5c1.png)

Here is my autoload_psr4.php:
![prs4](https://user-images.githubusercontent.com/9609925/82829649-11e8e900-9eb4-11ea-8b4b-4779e56fbed8.jpg)

Does someone struggle with the same issue and has a solution for it?

Best regards

**Comment by liayn** [comment]
@juergenweb it would be better to create a new issue if you see a different error message.
Please don't forget to add, how to reproduce the issue. So what did you do until you got this error.

**Comment by juergenweb** [comment]
OK, sorry. I only read the first parts of the path and did not recognize that this is not the same issue. My fault.

**Comment by georgringer** [comment]
@liayn had this issue as well on non-composer based installation, typo3 9.5.17, win10, php 7.4.2, 

psr-4 looks good and it is not only this class but if removed from controller, other classes as well. I didn't really had time to debug that as it was a remote session

**Comment by liayn** [comment]
@georgringer see #286. Loading of the classes failed due to PHP coding errors (PHP compatibility)
This is fixed now.
