### ISSUE TITLE
Exception after extension activation if tx_flux also installed

### ISSUE THREAD

**Issue by BenjaminBeck** [FriendsOfTYPO3/extension_builder#20]
I do have this issue for a really long time now and i wonder why nobody else has the same problem?!

The Exception is ``#1289843275: "extensionName" is not properly configured. Request can't be dispatched! ``

Any idea?

TYPO3: Current dev-master
Other Extensions: vhs, flux, realurl, ..

![screenshot 2017-03-02 23 15 15](https://cloud.githubusercontent.com/assets/1185872/23529588/781672be-ff9e-11e6-982f-11cd634afa5a.png)

**Comment by nicodh** [comment]
Can you post your ext_localconf.php ? That's the file where the extension name is configured as the first argument for the configurePlugin method...

**Comment by BenjaminBeck** [comment]
I found the problem. tx_flux does also provide a configurationManager implementation. When requesting just the configurationManagerInterface this other configurationManager implementation is been delivered.
In BenjaminBeck@af1d9d153a000a3767ff8a1da68df5f7a8321906 i made a quick workaround that works for me, but i think this issue needs some structural change in extension_builder.

**Comment by nicodh** [comment]
Can you please check if this happens still with current TER version (7.6.18)

**Comment by markuspoerschke** [comment]
We also expirienced this bug. I just tested this extension with version `7.6.16` and it was broken displaying the mentionend exception. After installing `7.6.18` the exception messages disappeared. To me it looks like the issue is solved.

Thank you!
