### ISSUE TITLE
not functional

### ISSUE THREAD

**Issue by hgalt** [FriendsOfTYPO3/extension_builder#203]
Under 9.5.6 I downloaded the newest version from the git.
Installing was ok, but after open the extension I only can see in theupper right side
Icon: open in new window
Drop down box: Domain modelling

Nothing else.

**Comment by liayn** [comment]
I just tested latest master from git and current 9.5.7-dev. There is not much of a difference to 9.5.6. I have no issues at all.
Is your remaining installation working correct?

Please check the developer console of your browser and the various logs (PHP error log, typo3temp/var/logs/, etc) for messages that would indicate an error.

**Comment by hgalt** [comment]
PHP error and log files includes no error.
But developer console shows:
TypeError: TYPO3.jQuery is not a function
This was already an old issue #140

**Comment by hgalt** [comment]
Here a screen shot
![ExtBuildner](https://user-images.githubusercontent.com/6670160/57777447-38f9d000-7722-11e9-8dae-4c6d74cdec50.jpg)

**Comment by liayn** [comment]
Is it possible that your browser cached old files of extension_builder somehow?
The extension's code does not contain any reference to `TYPO3.jQuery` anymore.

**Comment by hgalt** [comment]
I have downloaded the files again. Deleated all files unter the directory extension:builder and copy the no ones.
Now it works.
I guess there was maybe a file from a older version, which created that problem.
Thanks for you support!
