### ISSUE TITLE
Typo3 v9.5 - Cannot install latest version of the extension

### ISSUE THREAD

**Issue by pmartin-sword** [FriendsOfTYPO3/extension_builder#204]
On Typo3 v9.5.5, when i try to install the extension from the extension manager, i do not find the latest version of extension_builder but the "8.10.4 Beta" version. When i'm trying to install this version, the page of the Extensions builder - domain modeling is still blank with a JS error.

On the typo3 documentation website, there is the version 8.10.4 beta (https://docs.typo3.org/typo3cms/extensions/extension_builder/Index.html#), same as the extensions website (https://extensions.typo3.org/extension/extension_builder/).

Could you please give me any information about the latest version on GitHub and how to get it in the extension manager ?

Thank you in advance for your help, 

Pierre

**Comment by liayn** [comment]
For TYPO3 v9.5.x you should get the latest version here from git.

**Comment by apiening** [comment]
I have installed `extension_builder` via composer to my TYPO3 9.5.5 instance. Is this ok as well, or should I clone the git repo instead?

**Comment by liayn** [comment]
if you used dev-master as version requirement then this is fine

**Comment by pmartin-sword** [comment]
Thank you for the answer. 
Do you plan to deploy this new version into typo3 extension repository ? As well as the previous versions ?

Regards

**Comment by nicodh** [comment]
New version is planned to publish in TER, previous versions not.
But since most developers will use composer there is no high priority on this...

**Comment by apiening** [comment]
> if you used dev-master as version requirement then this is fine

Thanks. I had `"friendsoftypo3/extension-builder": "^9.10"` in my requirements but changed the version to `dev-master`.
