### ISSUE TITLE
TYPO3 9.5.x TER

### ISSUE THREAD

**Issue by rafu1987** [FriendsOfTYPO3/extension_builder#206]
Hey there and thanks for your great extension.

When will you upload the newest version for TYPO3 9.5.x to the TER?

Thanks in advance :-)

**Comment by fabtho** [comment]
Can you just do this? Not everyone has a look at this repro and know hot to use git. Or can I make a friendly fork of this and deploy it to TER?

**Comment by liayn** [comment]
@fabtho Please join us on Slack in the #extension_builder channel. I guess it's best to talk to Nico there directly regarding this.
