### ISSUE TITLE
Generated documentation not up to date

### ISSUE THREAD

**Issue by sypets** [FriendsOfTYPO3/extension_builder#207]
There are several issues with the rendered documentation. Especially the thing with the TABs may lead to mixing of TABs and spaces and subsequent incorrect indenting and problems with rendering.

Some things changed over the years and are now being done differently. Additionally, I would try to simplify things, to make it as easy as possible for people to create and maintain their documentation.

1. **important:** Generated docs are using TABs. The current coding guidelines of official TYPO3 documentation use 3 spaces, not TABs per indenting level, see [Writing Documentation](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/CodingGuidelines.html#whitespace-and-indenting). 
2. **important:** `Documentation/Settings.cfg` is now being used, `Settings.yml` can be removed, see [Directories and Filenames in "Writing Documentation"](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/DirectoryFilenames.html#settings-cfg)
3. **recommended:** The directive `.. only:: html` on the start page is unnecessary (as we do not generate PDF anymore). The subsequent indexing is unnecessary. 
4. **recommended:** Creative Commons now being used, see https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/Licenses.html

Additionally, the [Example Extension Manual](https://github.com/TYPO3-Documentation/TYPO3CMS-Example-ExtensionManual) has been improved further. You may want to base the generated documentation on this. 

before:

```
=============================================================$
Sybi Test$
=============================================================$
$
.. only:: html$
$
^I:Classification:$
^I^Isybitest$
$
^I:Version:$
^I^I|release|$
```
_^ are TABs
$ are end of line_

We would have:

```
=============================================================$
Sybi Test$
=============================================================$
$
:Classification:$
   sybitest$
$
:Version:$
   |release|$
```

**Comment by liayn** [comment]
Hi @sypets! How much effort would you estimate this would be to to update the docs? You have far more experience in this, that's why I'm asking.

**Comment by sypets** [comment]
@liayn It depends. I can offer to create a PR for this. I already looked at the doc generation process and it looks quite straightforward. We are currently making a few more changes to the Extension example, so it might take a few days. 

In general, we want to do more to support extension authors in their documentation efforts. I think it is a good step to also simplify the extension doc example.

**Comment by liayn** [comment]
Thanks. Take the time you need, your help is very much appreciated in this area.
