### ISSUE TITLE
Changing the way PHP files are auto-formated

### ISSUE THREAD

**Issue by qbadev** [FriendsOfTYPO3/extension_builder#215]
I don't like the way PHP files are formated, after auto-generating class files etc. I would like to change it to be more readable and usable for myself. How can this be achieved?

**Comment by liayn** [comment]
There is no way to modify this behavior without changing code in the extension_builder itself.
Generally there is only 1 way PHP files should/must be formatted and that regulated in the standards PSR-1, PSR-2 and upcoming PSR-12 (the last one is to be preferred).

**Comment by qbadev** [comment]
Where can I modify it? I understand the standards, but I need the code to fit my needs. "Democracy" is not the way I live as developer ;-) I do not follow the majority. I will modify it but please point me to right direction. Thanks

**Comment by nicodh** [comment]
Well first approach would be to add your own Templates here:
https://github.com/FriendsOfTYPO3/extension_builder/blob/master/ext_typoscript_setup.txt

But that is not tested and there might be parts that are not taken from Templates but ViewHelper etc.

**Comment by qbadev** [comment]
BTW it's not compliant with PSR-12, as in my php files curly bracket '{' in function declaration are in the same line as function name itself.
I took an example of PSR-12 from here: [https://www.php-fig.org/psr/psr-12/]()

**Comment by nicodh** [comment]
Hmm, that should not be the case in new generated files...

**Comment by nicodh** [comment]
If you look at the fixtures you see they all have a new line after function name:
https://github.com/FriendsOfTYPO3/extension_builder/tree/master/Tests/Fixtures/TestExtensions/test_extension/Classes

**Comment by nicodh** [comment]
You may also extend https://github.com/FriendsOfTYPO3/extension_builder/blob/master/Classes/Service/Printer.php and/or https://github.com/FriendsOfTYPO3/extension_builder/blob/master/Classes/Service/FileGenerator.php which should enable you to do almost everything different as it is done right now.
btw: any PRs improving formatting for better support of PSR-12  are welcome

**Comment by qbadev** [comment]
Maybe new files are fine. But compiler/formatter changes my changes, i.e. using curly brackets in function name lines even if I just changed it to be in next line. That's exactly my problem, as I format old-files myself plenty of times, and then after changing sth in EB BE panel, old-files are reformatted.

Thanks 4 Ur response.

**Comment by nicodh** [comment]
You can always exclude files from being rewritten in the overwrite settings

**Comment by qbadev** [comment]
It is convenient to add new fields to model and have all necessary functions added automatically, so I don't want to exclude any files.
