### ISSUE TITLE
incorrect escaping of html-chars

### ISSUE THREAD

**Issue by rvock** [FriendsOfTYPO3/extension_builder#24]
If the extension name or the extension description contains an ampersand (&) it will be escaped while writing for example ext_emconf.php or ext_tables.php.

This leads to a double-escaped ampersand in the extension builder, because the title will be escaped again.

I think, it should be enough to quote the strings and use raw-output for the rest:
```php
$EM_CONF[$_EXTKEY] = [
    'title' => '<f:format.raw><k:format.quoteString>{extension.name}</k:format.quoteString></f:format.raw>',
    'description' => '<f:format.raw><k:format.quoteString>{extension.description}</k:format.quoteString></f:format.raw>',
```

**Comment by BenjaminBeck** [comment]
Found the same problem in: ``/Resources/Private/CodeTemplates/Extbase/Configuration/TCA/Overrides/tableName.phpt``
Every ``'`` did become ``&#039;``
I solved it with:
``<f:format.raw>$GLOBALS['TCA']['{domainObject.databaseTableName}']['columns'][$GLOBALS['TCA']['{domainObject.databaseTableName}']['ctrl']['type']]['config']['items'][] = ['LLL:EXT:{domainObject.extension.extensionKey}/Resources/Private/Language/locallang_db.xlf:{domainObject.mapToTable}.tx_extbase_type.{domainObject.recordType}','{domainObject.recordType}'];</f:format.raw>``
