### ISSUE TITLE
Make prerequisites extbase and fluid clearer

### ISSUE THREAD

**Issue by sypets** [FriendsOfTYPO3/extension_builder#249]
This is not a general extension builder for TYPO3, it is a tool that generates extensions based on Extbase / Fluid.

In fact, it is not possible to get it to just create a minimal extension without this:

* you must create a model, otherwise the extension_builder will fail on save. This will then create an Extbase repository, an Extbase model and controllers depending on your actions. And Fluid templates.

So, unless this is to be changed, I would propose to make this more clear in the naming and the requirements. 

* Rename title to "Extbase / Fluid Extension Builder"
* Add extbase and fluid as requirements in composer.json

**Comment by liayn** [comment]
> Rename title to "Extbase / Fluid Extension Builder"

Personally I think this is a bit bumpy, but maybe "Extbase Extension Builder" would fit.

> Add extbase and fluid as requirements in composer.json

IMO this is not conveying any more meaning if we do so. extbase and fluid are *always* available in the system and therefore adding those requirements only adds complexity and has no impact.

Other than that we could maybe turn the idea around and let it generate empty extensions too, but I don't see the purpose for this.

**Comment by liayn** [comment]
@sypets Are you okay with closing this?

**Comment by sypets** [comment]
Yeah, I am ok. Thanks for taking the time!

I still stand with my initial proposal but I can think about other ways to achieve this (main goal was ultimately to make things more clear for people new to TYPO3).
