### ISSUE TITLE
Could not generate action controller

### ISSUE THREAD

**Issue by brotkrueml** [FriendsOfTYPO3/extension_builder#250]
When saving an created extension with activated default actions an error occurs:
![extension-builder-error](https://user-images.githubusercontent.com/2566282/70867005-b57eb680-1f70-11ea-9633-5a9c9068f765.png)

TYPO3: 9.5.11
Extension Builder: Commit d6b734f

**Comment by liayn** [comment]
Offending commit 5f24d2c6
https://github.com/FriendsOfTYPO3/extension_builder/commit/5f24d2c6#diff-bdd4818b841351a379847f8ee19d668fR802
The key of this array is used for preg_replace. 
`/\VENDOR\Package\Domain\Repository\DomainObjectRepository/` is an invalid regex as it seems. `\P` is a special sequence.
We need to quote the backslashes. (once for PHP, once for PCRE => 4 backslashes need in the PHP string)
`\\\\VENDOR\\\\Package\\\\Domain\\\\Repository\\\\DomainObjectRepository`

**Comment by nicodh** [comment]
I can't reproduce this and so I can't test the fix. The commit 5f24d2c just changes the order of the keys so I wonder why it worked before...

**Comment by liayn** [comment]
Right, the commit is the wrong one, I missed that.
I guess it depends on the PCRE version.
@brotkrueml Which PHP version are you using?

**Comment by brotkrueml** [comment]
I used ddev 1.10 (which should have PHP 7.2.21 or below), after updating to ddev 1.12 with PHP 7.2.25 I've got no error anymore.

**Comment by liayn** [comment]
Okay, still we should validate the regex again

**Comment by ohader** [comment]
Confirmed...

**Comment by ohader** [comment]
How to reproduce...

* create model being aggregate root
* let extension builder create controller with all actions
* persist extension to disk
* **NOW** manually modify controller and remove `inject` method
* go back to extension builder and persist it again

```
Extension could not be saved: Could not generate action controller, error: PHP Warning: preg_replace(): Compilation failed: unknown property name after \P or \p at offset 9 in /var/www/html/public/typo3conf/ext/extension_builder/Classes/Service/ClassBuilder.php line 661
```

**Comment by ohader** [comment]
Thanks to @rajatduggs & @brotkrueml for reporting this issue!
