### ISSUE TITLE
Call to a member function findAll() on null

### ISSUE THREAD

**Issue by Messa1** [FriendsOfTYPO3/extension_builder#259]
I just create over the extension a simple extension with one model.
I got following error `Call to a member function findAll() on null` in typo3conf/ext/mg_timeline/Classes/Controller/JahrController.php line 28

```php
class JahrController extends \TYPO3\CMS\Extbase\Mvc\Controller\ActionController
{

    /**
     * action list
     * 
     * @return void
     */
    public function listAction()
    {
        $jahrs = $this->jahrRepository->findAll();
        $this->view->assign('jahrs', $jahrs);
    }
```

I'm using Typo3 9.5.13

![Bildschirmfoto 2020-01-28 um 10 44 43](https://user-images.githubusercontent.com/3908658/73252655-5d67e080-41bb-11ea-8d93-f2a216814231.png)
![Bildschirmfoto 2020-01-28 um 10 44 40](https://user-images.githubusercontent.com/3908658/73252656-5d67e080-41bb-11ea-8d6e-23c6c20d893f.png)
![Bildschirmfoto 2020-01-28 um 10 44 35](https://user-images.githubusercontent.com/3908658/73252657-5d67e080-41bb-11ea-9b9b-6399e942ab86.png)
![Bildschirmfoto 2020-01-28 um 10 44 11](https://user-images.githubusercontent.com/3908658/73252658-5d67e080-41bb-11ea-94a5-a7edf6c8cd02.png)
![Bildschirmfoto 2020-01-28 um 10 43 57](https://user-images.githubusercontent.com/3908658/73252659-5e007700-41bb-11ea-9dc2-70b6deb37048.png)
![Bildschirmfoto 2020-01-28 um 10 48 19](https://user-images.githubusercontent.com/3908658/73252851-bb94c380-41bb-11ea-881d-99c8b26465fe.png)

**Comment by pquerner** [comment]
How is `jahrRepository` injected into your controller class ?

**Comment by zeichensatz** [comment]
To get `jahrRepository` injected to your controller, you have to check the option `Is aggregate root`.
