### ISSUE TITLE
Change signature of configurePlugin

### ISSUE THREAD

**Issue by nicodh** [FriendsOfTYPO3/extension_builder#261]
see https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-87550-UseControllerClassesWhenRegisteringPluginsmodules.html
and
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.1/Deprecation-88995-CallingRegisterPluginWithVendorName.html

**Comment by liayn** [comment]
Closing as it seems to be fixed with #299
