### ISSUE TITLE
ConfigurationManager constructor needs arguments 

### ISSUE THREAD

**Issue by nicodh** [FriendsOfTYPO3/extension_builder#262]
\EBT\ExtensionBuilder\Configuration\ExtensionBuilderConfigurationManager extends TYPO3\CMS\Extbase\Configuration\ConfigurationManager which needs   
@param \TYPO3\CMS\Extbase\Object\ObjectManagerInterface $objectManager
and
@param \TYPO3\CMS\Extbase\Service\EnvironmentService $environmentService
as constructor arguments in v10.x

I think we should not inherit from that class anymore but get configuration from a new instance of ConfigurationManager

**Comment by liayn** [comment]
Is this done?

**Comment by nicodh** [comment]
Yes
