### ISSUE TITLE
Use dependencies from current TYPO3 version

### ISSUE THREAD

**Issue by nicodh** [FriendsOfTYPO3/extension_builder#264]
If we support different versions we should reflect the current TYPO3 version in the dependencies of new generated extensions

**Comment by DavidBruchmann** [comment]
In the BE interface `Extension Properties` => `Target version` it was always the case, or do you talk about something else?

**Comment by liayn** [comment]
I would argue we only generate code for the current version of the Core. After all most new extensions are kickstarted for new projects hopefully done with the latest Core version.

**Comment by simonschaufi** [comment]
Since the EB is compatible with TYPO3 10 only, it doesn't make sense to generate extension code for older versions indeed. If you want to generate code for extensions for TYPO3 9 then install a EB version compatible with TYPO3 9.
