### ISSUE TITLE
Extending News show type selector twice

### ISSUE THREAD

**Issue by GuidoJansen** [FriendsOfTYPO3/extension_builder#267]
Versions
TYPO3: 9.5.14
Extension: Builder: 9.10.2-20200228

Extending News Model (famous news extension by Georg Ringer) yields in type field showing twice

This is my demonstration model
![image](https://user-images.githubusercontent.com/3098067/76201495-a3b95200-61f3-11ea-8908-882df96744c1.png)
![image](https://user-images.githubusercontent.com/3098067/76201544-b764b880-61f3-11ea-89e6-8a7147f0f199.png)

The TCA of the news model looks like this (only the relevant parts)
![image](https://user-images.githubusercontent.com/3098067/76201625-d3685a00-61f3-11ea-97f2-3bb8657fd6bb.png)

You see, the type field is shown twice with this configuration. First in the palette _paletteCore_, which is created by the news extension itself. And then after the title field by my generated demo extension.

This is generated by CodeTemplate `EXT:extension_builder/Resources/Private/CodeTemplates/Extbase/Partials/TCA/TypeField.phpt`

```
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addToAllTCAtypes(
    '{databaseTableName}',
    $GLOBALS['TCA']['{databaseTableName}']['ctrl']['type'],
    '',
    'after:' . $GLOBALS['TCA']['{databaseTableName}']['ctrl']['label']
);
```

**Can't we add a condition to this that only adds the type, if it doesn't exist before?**

**Comment by nicodh** [comment]
It looks as if you entered the value to both fields, extend table and extend class. Please use only one field at a time. The latter will result in using the same table anyway.
But: the news extension uses a different (special) approach to extend classes so it might not work as expected. If you want to extend news ask google how to do that properly.

**Comment by liayn** [comment]
Closing this due to lack of feedback.
