### ISSUE TITLE
TYPO3 10 compatible?

### ISSUE THREAD

**Issue by vicdev82** [FriendsOfTYPO3/extension_builder#276]
Are there any plans to make this extension Typo3 10 compatible?I find this extension very useful for people who are starting developing typo3 extensions and are not familiar with the structure.

Thanks.

**Comment by nicodh** [comment]
Yes there are - but I can't promise when...

**Comment by simonschaufi** [comment]
You can checkout my branch `v10-compatibility` in my fork if you need it urgently.

**Comment by Vicdev882** [comment]
> 
> 
> You can checkout my branch `v10-compatibility` in my fork if you need it urgently.

Thank you @simonschaufi I will take a look at it.

**Comment by liayn** [comment]
@simonschaufi @nicodh Do we want the `v10-compatibilility`-branch to be v10 only or v9+v10 compatible?
I would vote for v10 only.

**Comment by simonschaufi** [comment]
Since we have a 9.5 branch, I would continue v10 only. If we need to fix something for v9, we can push that to the 9.5 branch and make a separate release. I'm not a big fan of lots of compatibility layers.

**Comment by liayn** [comment]
Then we should probably merge the current master into the 9.5 branch now and declare master for v10 development

**Comment by simonschaufi** [comment]
yes!
