### ISSUE TITLE
After installation on Typo3 7.6.16 failure: "extensionName" is not properly configured

### ISSUE THREAD

**Issue by Terminator81** [FriendsOfTYPO3/extension_builder#28]
#1289843275: "extensionName" is not properly configured. Request can't be dispatched! (More information)

TYPO3\CMS\Extbase\Mvc\Exception thrown in file
/var/www/html/typo3_src-7.6.16/typo3/sysext/extbase/Classes/Mvc/Web/RequestBuilder.php in line 127.

can you help me?

**Comment by graebermedien** [comment]
same Problem here! Any hints how to fix that? Module is not usable ....

**Comment by nicodh** [comment]
Do you get this error after installing an extension which was created with the ExtensionBuilder or after installing ExtensionBuilder  itself?

**Comment by graebermedien** [comment]
after installing ExtensionBuilder itself?

**Comment by nicodh** [comment]
`EXTCONF 
     -> extbase
         - >extensions
              ->ExtensionBuilder
                    ->modules
                         ->tools_ExtensionBuilderExtensionbuilder
                              ->controllers
                                   ->BuilderModule
                                        ->actions
                                                  0 = index
                                                  1 = domainmodelling
                                                  2 = dispatchRpc

**Comment by graebermedien** [comment]
Seems to be an error in combination with "fluidcontent" (last stable version 4.4.1) -> after disabling fluidcontent it seems to work ---> any ideas how to fix this in fluidcontent?

**Comment by nicodh** [comment]
Can you please try, if this is fixed with #33 ?
It seems there was a conflict with the Flux ConfigurationManager...

**Comment by Terminator81** [comment]
i will try it tomorrow

**Comment by nicodh** [comment]
It should be fixed with current TER version (7.6.18)

**Comment by Terminator81** [comment]
now it works :) thanks
