### ISSUE TITLE
Extending from the User Table / Typo3 10.4 ?

### ISSUE THREAD

**Issue by docmcfly** [FriendsOfTYPO3/extension_builder#285]
Hello, 

i have a question: My "old" 9.5 extension (built with the extension_builder) added new attributes to fe_user. Since 10.4 this seems not to work anymore. 

In 9.5 the attributes were added directly to the fe_user table. 

Now I simply installed the extension_builder 10 compatible. I wanted to see how it is generated now. 

So I created a new model named "User" and added the following to "Extend existing model class": "\TYPO3\CMS\Extbase\Domain\Model\FrontendUser".

I received the following error message: 
"Extension could not be saved: Table definitions for table tx_extbase_domain_model_frontenduser could not be loaded. You can only map to tables with existing TCA or extend classes of installed extensions!

Is this a shortcoming of the extension_builder or a fundamental problem of Typo3: You can't extend standard tables just like that?

Thanks for your help 
Greetings Clemens

**Comment by DavidBruchmann** [comment]
It's a feature ;-)

Extension Builder is generating files that work within the extbase-logic and extbase is mapping tables automatically depending on the given names of the models - therefore in your case it's searching for the table "tx_extbase_domain_model_frontenduser".

Nevertheless there is a simple way to tell extbase to look for another table related to that model:

1. create a file in the root of your extension with the name `ext_typoscript_setup.typoscript`.
2. In that file map the correct table to the model class:
    ```
    config.tx_extbase.persistence.classes {
	\TYPO3\CMS\Extbase\Domain\Model\FrontendUser {
		mapping {
			tableName = fe_users
               }
       }
    ```

**Comment by simonschaufi** [comment]
@DavidBruchmann the class mapping does not work in TYPO3 10 any more.

**Comment by docmcfly** [comment]
Unfortunately, I have also determined that... and how should one build it now?

**Comment by DavidBruchmann** [comment]
@simonschaufi you've the corresponding CHANGELOG and perhaps a link how to do it now?

**Comment by DavidBruchmann** [comment]
@simonschaufi I found it:
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87623-ReplaceConfigpersistenceclassesTyposcriptConfiguration.html

**Comment by DavidBruchmann** [comment]
@docmcfly in the posted link is written that you've just not the mapping in a php-file which resides in `your_extension/Configuration/Extbase/Persistence/Classes.php`. So in the description it looks quite easy.

**Comment by DavidBruchmann** [comment]
Thank's @simonschaufi the hint was very useful!

**Comment by docmcfly** [comment]
@simonschaufi : Super super super super super ... thank you very much...

**Comment by docmcfly** [comment]
I have one more question... because this all sounds easy... ...but it doesn't work...


Before: (TypoScript)
config.tx_extbase {
    persistence {
        classes {
            TYPO3\CMS\Extbase\Domain\Model\FrontendUser {
                subclasses {
                    Tx_Usertools_User = Cylancer\Usertools\Domain\Model\User
                }
            }
            Cylancer\Usertools\Domain\Model\User {
                mapping {
                    tableName = fe_users
                    recordType = 0
                }
            }
        }
    }
}

After: (Classes.php)
<?php
declare(strict_types = 1);
return [
    TYPO3\CMS\Extbase\Domain\Model\FrontendUser::class => [
        subclasses => 
             [ 'Tx_Usertools_User' => 'Cylancer\Usertools\Domain\Model\User' ]
       ],        
    Cylancer\Usertools\Domain\Model\User::class => [
        "tablename" => "fe_users
    ]
];


Nevertheless, I am told by Typo3 
TYPO3\CMS\Extbase\Persistence\Generic\Storage\Exception\SqlErrorException

Table 't3_demo.tx_usertools_domain_model_user' doesn't exist

Anybody got any ideas?

Greeting Clemens

**Comment by DavidBruchmann** [comment]
Usually you should just extend \TYPO3\CMS\Extbase\Domain\Model\FrontendUser and never use it directly. Then it should be enough just to use this code for mapping;
```
<?php
declare(strict_types = 1);
return [ 
    Cylancer\Usertools\Domain\Model\User::class => [
        "tablename" => "fe_users
    ]
];
```

**Comment by DavidBruchmann** [comment]
If you use the namespaces correctly with leading back-slash, you version could work too though.

**Comment by docmcfly** [comment]
Thanks for your input. I'm afraid I still can't. 

When activating the extension the Classes.php is also executed. (I was able to check this with a built-in error. ;-) 

But if my controller uses the UserRepository (extends FrontendRepository) and calls #findByUid(...), the table t3_demo.tx_usertools_domain_model_user is missing. 

This looks like an error in Typo3? Does it?

**Comment by DavidBruchmann** [comment]
You're extending the wrong Repository, try it with this one:
```
\TYPO3\CMS\Extbase\Domain\Repository\FrontendUserRepository
```

**Comment by docmcfly** [comment]
Sorry - my typo - my repository inherits from the FrontendUserRepository... 

Otherwise this wouldn't have worked under 9.5 ;-) 

I'm going to open an issue at the Typo3-Core - maybe they can help me.  Then post the link right here... 

Greetings Clemens

**Comment by docmcfly** [comment]
Here is the link to the issue (my extension is also attached to this one) 

https://forge.typo3.org/issues/91388

Good night Clemens

**Comment by docmcfly** [comment]
i have found the solution: My mistake: 
tableName is right. 
tablename is wrong.
