### ISSUE TITLE
Class EBT\ExtensionBuilder\Domain\Validator\ExtensionValidator does not exist. Reflection failed.

### ISSUE THREAD

**Issue by juergenweb** [FriendsOfTYPO3/extension_builder#286]
Hello @all 

I get the following error after installing the Extension Builder via composer and clicking on the icon of the extension builder in the left menu bar.

![Screenshot](https://user-images.githubusercontent.com/9609925/82829297-40b28f80-9eb3-11ea-9856-232a1f1de5c1.png)

My settings:
TYPO3 9.5.18
PHP Version 7.4.5
Server-Version: 10.4.11-MariaDB
Apache/2.4.43
Extension Builder 9.10.2

The class is present in the file:

![classfile](https://user-images.githubusercontent.com/9609925/83026146-7bd9cd80-a02f-11ea-9a6e-7e8e0cb881d5.jpg)

Everything else in the backend works as expected. It only happens at starting the builder by clicking on the icon.

Here is my autoload_psr4.php:
![prs4](https://user-images.githubusercontent.com/9609925/82829649-11e8e900-9eb4-11ea-8b4b-4779e56fbed8.jpg)

Does someone else struggles with the same issue and has a solution (or explaination) for this error message?

Best regards

**Comment by liayn** [comment]
Please post the full stack trace of the exception thrown

**Comment by juergenweb** [comment]
Here are the 3 stack messages and the entry from the log file afterwards.

![stack-trace](https://user-images.githubusercontent.com/9609925/83136722-3fb67380-a0e8-11ea-8f75-c8efc1231050.jpg)

I hope this contains the information you need to know. I am new to T3, so if you mean another protocoll, please give me a hint where I can find this information.

Best regards Jürgen

**Comment by liayn** [comment]
Can you try using latest master from github here instead of 9.10.2 from TER?

**Comment by juergenweb** [comment]
Thanks for the hint, but unfortunately I get the same result. :-(

**Comment by liayn** [comment]
So the third error above (array or string offset) should be gone. Right?

**Comment by juergenweb** [comment]
No, but the line number has changend.

![Screenshot(1)](https://user-images.githubusercontent.com/9609925/83157173-94b3b300-a103-11ea-81f7-e132e4f8d233.png)

I am using PHP 7.4 - could this be a possible reason?

**Comment by liayn** [comment]
Okay, I fixed this error now, please pull the latest version.
PHP 7.4 should not matter when it comes to path resolution. But you could try with 7.3, if it's easily doable for you.

Can you debug code in your setup?
Would be interesting what the composer autoloader tries to load, when the `ExtensionValidator` is requested.

**Comment by juergenweb** [comment]
Thanks! I will try it and give you a feedback.

**Comment by juergenweb** [comment]
The old errors are gone, but now I get the following messages:

![Screenshot](https://user-images.githubusercontent.com/9609925/83160342-60da8c80-a107-11ea-9fe1-686969a71f47.png)
![Screenshot(1)](https://user-images.githubusercontent.com/9609925/83160352-633ce680-a107-11ea-9392-183d150daafc.png)
![Screenshot(2)](https://user-images.githubusercontent.com/9609925/83160365-659f4080-a107-11ea-982c-a76de569a1d0.png)

**Comment by liayn** [comment]
Okay, now I got a clue what's going on. The PHP parser reports all those "PHP Runtime Deprecations" which prevent the loading of the class. So it's actually a matter of code quality/PHP configuration and not class loading.
I fixed this issue now too.

Lets see if more issues pop up.
You can of course configure your php.ini to now report the PHP runtime deprecations, then this problem should vanish as well.

**Comment by juergenweb** [comment]
Ok now it works - here is the solution:

remove the following code from extension_builder/Classes/Service/ParserService.php around line 103

`  /**
     * @param string $code
     * @return array
     */
    public function parseRawStatements($code)
    {   
          return parent::parse($code);
    }`

This class is not extending another class so there is no parent present.  After removing this part of code the error messages were gone.
If you agree with me, you can close this issue. If I discover some other issues I will open a new report.

Thanks for your help!!!

**Comment by liayn** [comment]
I pushed this exact change 12 minutes ago ;-)
https://github.com/FriendsOfTYPO3/extension_builder/commit/69d580737e0b5d776b32629d0c3f6be4981748ee

As I said. Either fix code or disable those error message in php.ini

**Comment by simonschaufi** [comment]
@liayn can we make a bugfix release for this?

**Comment by liayn** [comment]
Only @nicodh can create releases in TER. So we have to wait for him.
