### ISSUE TITLE
Fix setRelationTableName feature for camel case properties

### ISSUE THREAD

**Issue by colorandcode** [FriendsOfTYPO3/extension_builder#287]
There is a feature to set the relation table name depending on an existing TCA configuration.

```
if (isset($existingTca['columns'][$relationProperty->getName()]['config']['MM'])) {
    $relationProperty->setRelationTableName(
        $existingTca['columns'][$relationProperty->getName()]['config']['MM']
    );
}
```

https://github.com/FriendsOfTYPO3/extension_builder/blob/master/Classes/Service/RoundTrip.php#L1079

That doesn't work if the property name is in camel case (exampleName), as in the TCA the column name is with underscores (example_name) and the if check returns false.

Quick workaround:

```
$GLOBALS['TCA']['tx_extension_domain_model_table1']['columns']['exampleName']['config']['type'] = 'none';
$GLOBALS['TCA']['tx_extension_domain_model_table1']['columns']['exampleName']['config']['MM'] = 'tx_extension_table1_examplename_table2_mm';
```

**Comment by DavidBruchmann** [comment]
In which file you place your workaround?
Just in the common table configuration in `EXT:my_ext/Configuration/TCA/my_table.php` or in `ext_tables.php`, or somewhere in the code?

**Comment by colorandcode** [comment]
You should put it into EXT:my_ext/Configuration/TCA/Overrides/my_table.php
