### ISSUE TITLE
generateEmptyGitRepository: .git could be a file

### ISSUE THREAD

**Issue by donnnar** [FriendsOfTYPO3/extension_builder#288]
The function FileGenerator->generateEmptyGitRepository leads to an error, if ".git" is a file instead of a directory. This is possible, if your extension is a git submodule.

```
protected function generateEmptyGitRepository()
    {
        $targetDirectory = $this->extensionDirectory . '.git/';
        if (is_file($targetDirectory) || is_dir($targetDirectory) || is_link($targetDirectory)) {
            return;
        }
...
```

Should be something like that:
```
protected function generateEmptyGitRepository()
    {
        $targetDirectory = $this->extensionDirectory . '.git/';
        if (is_file($this->extensionDirectory . '.git') || is_dir($targetDirectory) || is_link($targetDirectory)) {
            return;
        }
...
```

**Comment by liayn** [comment]
Thanks for you report. Wanna push a pull request for this change?

**Comment by donnnar** [comment]
I'm sorry, but I have no experience in creating pull requests. I tried and I got an 403 Error Code. The fix in my comment resolves the bug:

```
if (is_file($this->extensionDirectory . '.git') || is_dir($targetDirectory) || is_link($targetDirectory)) {
```

**Comment by simonschaufi** [comment]
It's never too late for the first PR ;) You need to fork the repo first, create a new branch from master and then you can do a PR.

**Comment by simonschaufi** [comment]
By the way, I advice you to use composer instead of git submodules. Composer is much better for handling dependencies. If you want to know how to do it, I can help.

**Comment by donnnar** [comment]
> It's never too late for the first PR ;) You need to fork the repo first, create a new branch from master, push that branch and then you can do a PR.

I've done my first pull request. Thanks for your guidance. :)

> By the way, I advice you to use composer instead of git submodules. Composer is much better for handling dependencies. If you want to know how to do it, I can help.

That's a great advice. I think this will solve some issues we have with submodules. Thanks for that.
