### ISSUE TITLE
composer.json is generated as package.json

### ISSUE THREAD

**Issue by t3easy** [FriendsOfTYPO3/extension_builder#29]
Any reason for that?

**Comment by nicodh** [comment]
Maybe you have a "nightly build" which was only available for some hours? This was fixed with
https://github.com/FriendsOfTYPO3/extension_builder/commit/7fb6883c958d260ce5a003614cf2a920dc4dd9f7
This should not happen any more...

**Comment by nicodh** [comment]
Ok, I just realized that branch 8.6 had missing merges from master, perhaps that was the reason...

**Comment by t3easy** [comment]
Thank you @nicodh!
So which branch should I use for 8.6? `master` or `8.6`.

**Comment by nicodh** [comment]
At the moment they are same, but the plan is, to have a "stable" 8.6 for TER and a more experimental master in future
