### ISSUE TITLE
file settings.yaml not found on saving

### ISSUE THREAD

**Issue by DavidBruchmann** [FriendsOfTYPO3/extension_builder#302]
When referencing table or class in a model saving is failing with the message that settings.yaml can't be found.

With table:
![image](https://user-images.githubusercontent.com/999146/85267318-4e9e0500-b49f-11ea-900a-a53fd701432d.png)

With class:
![image](https://user-images.githubusercontent.com/999146/85267389-69707980-b49f-11ea-8ab4-fb3f7c7f2235.png)

**Comment by simonschaufi** [comment]
Please also let me know which version are you using and if composer mode or TER

**Comment by DavidBruchmann** [comment]
I'm using extenion_builder dev-master and it's a composer-setup.

**Comment by zeichensatz** [comment]
@DavidBruchmann, did you check permissions in your extension folder?
I get the same error message for a extension, where the permissions are not set right.
"chown -R wwwrun:www *" did fix the problem for me.

**Comment by DavidBruchmann** [comment]
file permissions are not an issue.
Sometimes windows is throwing an error when the folder never exists, in older versions I created the folder and everything went like expected then.
Here the problem is different and I don't know how to solve it with simple tricks.

**Comment by DavidBruchmann** [comment]
Question in the other direction is if you succeed with one or both models like I did create, @zeichensatz ?

**Comment by zeichensatz** [comment]
@DavidBruchmann just checked the first model and got this message:
<img width="866" alt="Bildschirmfoto 2020-06-22 um 16 58 27" src="https://user-images.githubusercontent.com/45975889/85302926-14863080-b4aa-11ea-9780-9780f050d4e4.png">
I was able to save the extension hitting ok.

**Comment by DavidBruchmann** [comment]
ok, thanks for testing I will check it again. The shown message is known and no problem.

**Comment by liayn** [comment]
Closing this due to lack of feedback.
