### ISSUE TITLE
Error when using Image/File Properties or a relation to an External Class

### ISSUE THREAD

**Issue by WebWinki** [FriendsOfTYPO3/extension_builder#304]
When i use a property of the Type Image/File or an Relation that is pointing to an external Class i get the following error whe saving:
`
Return value of EBT\ExtensionBuilder\Domain\Model\DomainObject\Relation\AbstractRelation::getForeignModel() must be an instance of EBT\ExtensionBuilder\Domain\Model\DomainObject, null returned`

![grafik](https://user-images.githubusercontent.com/67637037/86129274-b88f5d80-bae2-11ea-8f2b-5734bcc31716.png)

i also have the solution/reason for problem but i have trouble with github right now so i post it here:
Domain/Model/Relation/AbstractRelation.php

```
    protected $foreignModel = null;
    public function getForeignModel(): ?DomainObject
```

make that nullable again like in the older version and it works

**Comment by liayn** [comment]
Sounds very reasonable. Can you provide a pull request against the master branch please with your change suggestion?

**Comment by simonschaufi** [comment]
Please provide a screenshot of what you are doing to reproduce. There was another bug report about this already but that was because of wrong usage of the wire.

**Comment by WebWinki** [comment]
Done. Hope i did everything correctly. never contributed on github before :)

**Comment by simonschaufi** [comment]
I'm not so much interested in the error as the models and the wires

**Comment by WebWinki** [comment]
you just need to make a Model with a property of type Image to reproduce it. i haven't done anything else, and this is in the screenshot :)
