### ISSUE TITLE
v-10-compatibility, Error when saving a Model that extends an existing Model Class

### ISSUE THREAD

**Issue by WebWinki** [FriendsOfTYPO3/extension_builder#306]
Im trying to extend the Model FrontendUser but when saving i get the following error Message:
`Extension could not be saved: Table definitions for table tx_extbase_domain_model_frontenduser could not be loaded. You can only map to tables with existing TCA or extend classes of installed extensions!`

to reproduce you have to use the v10 Branch and the issue #304 has to be fixed already.
![grafik](https://user-images.githubusercontent.com/67637037/86229932-b388e780-bb90-11ea-9828-9a63e8758f22.png)

Reason for the error and "partial" solution:
in ExtensionSchemaBuilder->build() the function
`$classSettings = $this->configurationManager->getExtbaseClassConfiguration($domainObject->getParentClass());`
calls the following extbase function which returns in v10 different information it seems:
`$frameworkConfiguration = $this->configurationManager->getConfiguration($this->configurationManager::CONFIGURATION_TYPE_FRAMEWORK);`

in ExtensionSchemaBuilder->build() you could substitute it with
`$objectManager->get( \TYPO3\CMS\Extbase\Persistence\Generic\Mapper\DataMapper::class)->getDataMap($className)->getTableName()`
but i haven't checked the other occurrences of "getExtbaseClassConfiguration"

**Comment by DavidBruchmann** [comment]
Having done the replacement I get further errors:

 1. The directory uploads/tx_extensionmanager/backups never exists (I created it manually).
 2. Extension could not be saved: Could not generate TCA files, error: No class name was given to retrieve the Data Map for typo3\sysext\extbase\Classes\Persistence\Generic\Mapper\DataMapper.php

I tried to create the model on base of table sys_template.

**Comment by Moongazer** [comment]
I just run into the same issue on `dev-v10-compatibility`, trying to define a classes based on `fe_users` and `tt_content`: "Extension could not be saved: Could not generate TCA files, error: No class name was given to retrieve the Data Map for./var/www/html/public/typo3/sysext/extbase/Classes/Persistence/Generic/Mapper/DataMapper.php"

If I remove the table names from the model-objects, the generation continues without this error, until another error occurs: "Error while saving: Server responded with Status-Code: 500 Statustext: Internal Server Error". The popup shows:

**Argument 1 passed to EBT\ExtensionBuilder\Domain\Model\ClassObject\MethodParameter::setTypeHint() must be of the type string, null given, called in /var/www/html/public/typo3conf/ext/extension_builder/Classes/Service/ClassBuilder.php on line 451**

I tried to debug to find out where it comes from, but wasn't successful. It just seems during the generation of an `addMydomain()` method the `$domainProperty->getForeignClassName()` returns NULL.

**Comment by DavidBruchmann** [comment]
@Moongazer  Sure it would be nice having that  fixed but you can do it without that table(s) too and afterwards you just have to create the mapping-file manually: https://docs.typo3.org/m/typo3/book-extbasefluid/10.4/en-us/6-Persistence/4-use-foreign-data-sources.html

**Comment by lechenbauer** [comment]
Had the same error in v10, but current [10-compatibility branch](https://github.com/FriendsOfTYPO3/extension_builder/tree/v10-compatibility) with patch [fcdd003](https://github.com/FriendsOfTYPO3/extension_builder/commit/fcdd003c07854054ca8287c2f69f523187c6c333) works for me (extending tt_content)!

**Comment by liayn** [comment]
Closing this issue then.

**Comment by lechenbauer** [comment]
Would be nice if patch [fcdd003](https://github.com/FriendsOfTYPO3/extension_builder/commit/fcdd003c07854054ca8287c2f69f523187c6c333) could be merged into the 10-compatibility branch :)

**Comment by nicodh** [comment]
I created a PR https://github.com/FriendsOfTYPO3/extension_builder/pull/340

**Comment by liayn** [comment]
Sorry, I mistakenly thought this was already the case.

**Comment by simonschaufi** [comment]
done
