### ISSUE TITLE
exception: ReflectionException... (V10)

### ISSUE THREAD

**Issue by criwe** [FriendsOfTYPO3/extension_builder#307]
Hi all!
I think I´ve found a error (but may someone can test/confirm) in the V10 Version of that extension: I´ve build a simple test extension with one model object (and to keep it simple, only two properties). I can add entries in the backend -> fine.

But when I insert the FE plugin, an error occurs. Looking in the errorlog, I got the following message: 

`component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": Oops, an error occurred! Code: 202007241644340f8161fd5 - {"exception":"ReflectionException: Class Aaaaaaa\\Controller\\BbbbbController does not exist in typo3_src-10.4.5/typo3/sysext/extbase/Classes/Reflection/ClassSchema.php:127\nStack trace:\n#0 typo3_src-10.4.5/typo3/sysext/extbase/Classes/Reflection/ClassSchema.php(127): ReflectionClass->__construct('Aaaaaaa\\\\Cont...')\n#1`

I did not modify anything at this extension manualy. When looking in the class-file, it look fine.
There is a reference to the class-file in the autoload_classmap.php too. 

Would be great, if someone can make that simple test too! Maybe I missed some configuration?!
Thanks!
Best,
Christoph

TYPO3 10.4.5
Extensionbuilder 9.11.0
PHP 7.2

**Comment by simonschaufi** [comment]
Hi, the v10 branch is still far from being stable. There is still a lot to be done. Maybe you want to contribute code and help us finish it?

**Comment by nicodh** [comment]
I can't reproduce this. Are you in composer mode? Did you run 
composer require your/extension 
with the name as written in composer.json

**Comment by criwe** [comment]
@nicodh no, I´m not in the composer mode. Maybe something´s weird in my installation. In that case -> we can close that issue?
@simonschaufi I can help testing, but my programming skills are not sufficient to contribute :-(

**Comment by liayn** [comment]
Is this still an issue?

**Comment by criwe** [comment]
As it was not reproduceable we can close that issue.
