### ISSUE TITLE
Some existing icons are not loaded

### ISSUE THREAD

**Issue by gromerop** [FriendsOfTYPO3/extension_builder#31]
Hello.
When you mouse over a model object or one of the people linked to a project, some icons are not loaded. It is necessary to modify the routes of the icons.
![img01](https://cloud.githubusercontent.com/assets/16311347/24222387/e13b004e-0f1f-11e7-9f02-c19fd39eb5b0.png)
![img02](https://cloud.githubusercontent.com/assets/16311347/24222388/e13b3b18-0f1f-11e7-9455-8b3a5f8bb7d3.png)

**Comment by nicodh** [comment]
What is the icon path in your instance?
Should be something like:
/typo3/sysext/core/Resources/Public/Icons/T3Icons/actions/actions-edit-delete.svg

**Comment by floen-de** [comment]
I have the same problems. (TYPO3 7.6 - ext:extension_builder: 7.6.18)
I use subdirectorys. 
i.e.:  domain.org/project/typo3/

For me relative Urls works:

```
-                         delButton.innerHTML = '<span class="icon-markup"><img src="/typo3/sysext/core/Resources/Public/Icons/T3Icons/actions/actions-edit-delete.svg" width="16" height="16"></span>';
+                         delButton.innerHTML = '<span class="icon-markup"><img src="./sysext/core/Resources/Public/Icons/T3Icons/actions/actions-edit-delete.svg" width="16" height="16"></span>';

```

**Comment by liayn** [comment]
I can confirm. The "new icons" commit 1deda45 is faulty. An extension must never make any assumptions about its location or URL location. It should use Core API here to generate correct URLs.

**Comment by liayn** [comment]
@nicodh IMO the commit only fixed this for 8 but not for 7, so this has to be reopened

**Comment by nicodh** [comment]
Yes you're right. Will backport it soon...
