### ISSUE TITLE
v-10-compatibility: getForeignModel if allowed numbers of files is greater than 1

### ISSUE THREAD

**Issue by rangerluke** [FriendsOfTYPO3/extension_builder#316]
If you have a model with a property of type image or file and the allowed number of files is greater than 1 an error occured.
I tried to fix the error, but i didn't found the correct position.
![Auswahl_797](https://user-images.githubusercontent.com/1242161/94107300-73f33400-fe3d-11ea-8394-91cba3ed2b7c.png)

**Comment by DavidBruchmann** [comment]
you've to return a new empty Model (in your case ...\Model\DomainObject) if $this->foreignModel is null.

**Comment by DavidBruchmann** [comment]
is related to #304 / #305  
can be closed IMO
