### ISSUE TITLE
BE rootpaths not correct

### ISSUE THREAD

**Issue by hgalt** [FriendsOfTYPO3/extension_builder#325]
I have created a new extension and tried to edit the BE view.
But instead of getting the list from the directory Backend the list view from the FE will be shown!

For the FE the rootpath is already switched to the array, but for the module it is not changed to arrays.
I have figured out on another place that only arrays for the ...RootPaths are working in 9.5.22.

So please change the setup and constants.typoscript !

I tried to modify it by myself, but it did not work.

setUp:
```
# Module configuration
module.tx_imagetext_tools_imagetextbeimagetext {
    persistence {
        storagePid = {$module.tx_imagetext_beimagetext.persistence.storagePid}
    }
    view {
        templateRootPaths.0 = EXT:imagetext/Resources/Private/Backend/Templates/
        templateRootPaths.1 = {$module.tx_imagetext_beimagetext.view.templateRootPaths.0}
        partialRootPaths.0 = EXT:imagetext/Resources/Private/Backend/Partials/
        partialRootPaths.1 = {$module.tx_imagetext_beimagetext.view.partialRootPaths.0}
        layoutRootPaths.0 = EXT:imagetext/Resources/Private/Backend/Layouts/
        layoutRootPaths.1 = {$module.tx_imagetext_beimagetext.view.layoutRootPaths.0}
    }
}
```
constants:
```
module.tx_imagetext_beimagetext {
    view {
        # cat=module.tx_imagetext_beimagetext/file; type=string; label=Path to template root (BE)
        templateRootPaths.0 = EXT:imagetext/Resources/Private/Backend/Templates/
        # cat=module.tx_imagetext_beimagetext/file; type=string; label=Path to template partials (BE)
        partialRootPaths.0 = EXT:imagetext/Resources/Private/Backend/Partials/
        # cat=module.tx_imagetext_beimagetext/file; type=string; label=Path to template layouts (BE)
        layoutRootPaths.0 = EXT:imagetext/Resources/Private/Backend/Layouts/
    }
    persistence {
        # cat=module.tx_imagetext_beimagetext//a; type=string; label=Default storage PID
        storagePid = 30
    }
}
```
What did I wrong?

Edit:

I don't know, what the original problem was (maybe not cleared cache), but the modification from ...RootPath to ...RootPaths.x solved the problem!!!

**Comment by liayn** [comment]
Which version of extension_builder are you using?
What are the steps to reproduce the problem?

**Comment by hgalt** [comment]
GitHub from Yesterday. But the first version was created with the one in TER. But I have updated the extension with the GitHub.

**Comment by liayn** [comment]
Are you developing for v9 or v10?
Did you use the `master` branch or `v10-compatiblity` branch?
The latter are vastly different and we basically aim to get the v10 compatibility done.

**Comment by hgalt** [comment]
V9 master

**Comment by hgalt** [comment]
I would like to tell you, that with the changed configuration, mentioned in my first  part, I get it working!

**Comment by liayn** [comment]
Okay, I'm actually lost now.

Can you please rephrase what the problem currently is, and what the desired output must be?
Most important: We currently do not focus on the v9 version anymore, we target v10 as the current stable version

**Comment by hgalt** [comment]
The problem is the generation of the modul in the typoscripts constants and setup. 
On top I have put the parts, how the should be! But the extension builder is using the old  versions of ... PathRoot and not the araay of ...PathRoots.x!
So the newest version of V9.4.x is not longer working with this old version and I think V10 will be the same.
For the frontend is was changed already, but not for the BE.
Is it understandable?

**Comment by liayn** [comment]
Okay got it now. Thanks.
Can you push a pull request for this matter? Best would be for master and for the v10-branch if necessary.

**Comment by hgalt** [comment]
@liayn I don't know exactly what you mean. 
My understanding is, that a pull request is a code change, is this right?
I currently only know what has to change, but not how to do it in the code.
Could you help me?

**Comment by liayn** [comment]
Correct.
The files you wanna look at are
https://github.com/FriendsOfTYPO3/extension_builder/blob/master/Resources/Private/CodeTemplates/Extbase/Configuration/TypoScript/constants.typoscriptt
https://github.com/FriendsOfTYPO3/extension_builder/blob/master/Resources/Private/CodeTemplates/Extbase/Configuration/TypoScript/setup.typoscriptt

But the code there looks correct to me.

**Comment by hgalt** [comment]
@Lianyn I have test it again with an new extension setup. I also could not find any problem. Also with the versio 9.10.3.
Sorry, but I am not to figure out what my original problem was and which version I was using.
Thank you very much and sorry for wasting your time.

**Comment by liayn** [comment]
yw.
