### ISSUE TITLE
Icons are missing

### ISSUE THREAD

**Issue by rvock** [FriendsOfTYPO3/extension_builder#326]
Since TYPO3 10.4.10 many icons are missing. This happened because the location of the icons were moved:
https://forge.typo3.org/issues/92689#note-13

```
OLD: sysext/core/Resources/Public/Icons/T3Icons/actions/actions-move-up.svg
NEW: sysext/core/Resources/Public/Icons/T3Icons/svgs/actions/actions-caret-up.svg
```

**Comment by liayn** [comment]
Yes, should be changed to iconIdentifier

**Comment by rvock** [comment]
Those paths were within the JavaScript files. So it might be a bit harder to change to icon identifiers:

https://github.com/FriendsOfTYPO3/extension_builder/blob/dc88dc9865a8b3314b4f5ea18349d79fee5b10ce/Resources/Public/jsDomainModeling/wireit/lib/inputex/js/Field.js#L121
https://github.com/FriendsOfTYPO3/extension_builder/blob/dc88dc9865a8b3314b4f5ea18349d79fee5b10ce/Resources/Public/jsDomainModeling/extended/ListField.js#L258
https://github.com/FriendsOfTYPO3/extension_builder/blob/dc88dc9865a8b3314b4f5ea18349d79fee5b10ce/Resources/Public/jsDomainModeling/wireit/js/Container.js#L215

**Comment by liayn** [comment]
Okay, then we change those paths and we require the latest v10 in emconf and composer. easy.

**Comment by liayn** [comment]
should be resolved. closing.
