### ISSUE TITLE
Exception in NodeConverter when class contains nullable types

### ISSUE THREAD

**Issue by rvock** [FriendsOfTYPO3/extension_builder#327]
If a model contains a method with a nullable type, you get an exception when saving the extension:

```php
public function setImage(?FileReference $image): void {
	$this->image = $image;
}
```

The exception:
```
Argument 1 passed to EBT\ExtensionBuilder\Domain\Model\ClassObject\MethodParameter::setTypeHint() must be of the type string, null given, called in ...typo3conf/ext/extension_builder/Classes/Parser/ClassFactory.php on line 158
```

The fix is to check, if the node is an instance of a NullableType:
https://github.com/FriendsOfTYPO3/extension_builder/blob/dc88dc9865a8b3314b4f5ea18349d79fee5b10ce/Classes/Parser/Utility/NodeConverter.php#L120

```php
if ($node instanceof NullableType) {
    return '?' . self::getValueFromNode($node->type);
}
```

**Comment by liayn** [comment]
Can you push a PR please?
