### ISSUE TITLE
v-10-compatibility - [module-tools_ExtensionBuilderExtensionbuilder] The option "source" is required and must not be empty

### ISSUE THREAD

**Issue by sergeyvo80** [FriendsOfTYPO3/extension_builder#333]
typo3 - 10.4.10
	
> Oops, an error occurred! [module-tools_ExtensionBuilderExtensionbuilder] The option "source" is required and must not be empty

> Fri, 11 Dec 2020 09:39:31 +0100 [CRITICAL] request="18640e8d8c7f3" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1460976566: [module-tools_ExtensionBuilderExtensionbuilder] The option "source" is required and must not be empty | InvalidArgumentException thrown in file /var/www/newsite-typo3/public/typo3/sysext/core/Classes/Imaging/IconProvider/SvgIconProvider.php in line 37. Requested URL: https://newsite-typo3.local/typo3/index.php?route=%2Fmain&token=--AnonymizedToken--&referrer-refresh=1607674630 - {"TYPO3_MODE":"BE","exception":"InvalidArgumentException: [module-tools_ExtensionBuilderExtensionbuilder] The option \"source\" is required and must not be empty in /var/www/newsite-typo3/public/typo3/sysext/core/Classes/Imaging/IconProvider/SvgIconProvider.php:37\nStack trace:\n#0 /var/www/newsite-typo3/public/typo3/sysext/core/Classes/Imaging/IconProvider/AbstractSvgIconProvider.php(40): TYPO3\\CMS\\Core\\Imaging\\IconProvider\\SvgIconProvider->generateMarkup(Object(TYPO3\\CMS\\Core\\Imaging\\Icon), Array)\n#1 /var/www/newsite-typo3/public/typo3/sysext/core/Classes/Imaging/IconFactory.php(107): TYPO3\\CMS\\Core\\Imaging\\IconProvider\\AbstractSvgIconProvider->prepareIconMarkup(Object(TYPO3\\CMS\\Core\\Imaging\\Icon), Array)\n#2 /var/www/newsite-typo3/public/typo3/sysext/backend/Classes/Domain/Repository/Module/BackendModuleRepository.php(371): TYPO3\\CMS\\Core\\Imaging\\IconFactory->getIcon('module-tools_Ex...')\n#3 /var/www/newsite-typo3/public/typo3/sysext/backend/Classes/Domain/Repository/Module/BackendModuleRepository.php(294): TYPO3\\CMS\\Backend\\Domain\\Repository\\Module\\BackendModuleRepository->getModuleIcon('modmenu_tools', Array)\n#4 /var/www/newsite-typo3/public/typo3/sysext/backend/Classes/Domain/Repository/Module/BackendModuleRepository.php(47): TYPO3\\CMS\\Backend\\Domain\\Repository\\Module\\BackendModuleRepository->getRawModuleMenuData()\n#5 /var/www/newsite-typo3/public/typo3/sysext/core/Classes/Utility/GeneralUtility.php(3462): TYPO3\\CMS\\Backend\\Domain\\Repository\\Module\\BackendModuleRepository->__construct()\n#6 /var/www/newsite-typo3/var/cache/code/di/DependencyInjectionContainer_5ecfd83b67fb6e92085ea05e725290d13b5fe82d.php(3249): TYPO3\\CMS\\Core\\Utility\\GeneralUtility::makeInstanceForDi('TYPO3\\\\CMS\\\\Backe...')\n#7 /var/www/newsite-typo3/vendor/symfony/dependency-injection/Container.php(257): DependencyInjectionContainer_5ecfd83b67fb6e92085ea05e725290d13b5fe82d->getBackendModuleRepositoryService()\n#8 /var/www/newsite-typo3/vendor/symfony/dependency-injection/Container.php(231): Symfony\\Component\\DependencyInjection\\Container->make('TYPO3\\\\CMS\\\\Backe...', 1)\n#9 /var/www/newsite-typo3/public/typo3/sysext/core/Classes/Utility/GeneralUtility.php(3427): Symfony\\Component\\DependencyInjection\\Container->get('TYPO3\\\\CMS\\\\Backe...')\n#10 /var/www/newsite-typo3/public/typo3/sysext/backend/Classes/Controller/BackendController.php(107): TYPO3\\CMS\\Core\\Utility\\GeneralUtility::makeInstance('TYPO3\\\\CMS\\\\Backe...')\n#11 /var/www/newsite-typo3/public/typo3/sysext/core/Classes/Utility/GeneralUtility.php(3431): TYPO3\\CMS\\Backend\\Controller\\BackendController->__construct()\n#12 /var/www/newsite-typo3/public/typo3/sysext/core/Classes/Http/Dispatcher.php(86): TYPO3\\CMS\\Core\\Utility\\GeneralUtility::makeInstance('TYPO3\\\\CMS\\\\Backe...')\n#13 /var/www/newsite-typo3/public/typo3/sysext/backend/Classes/Http/RouteDispatcher.php(64): TYPO3\\CMS\\Core\\Http\\Dispatcher->getCallableFromTarget('TYPO3\\\\CMS\\\\Backe...')\n#14 /var/www/newsite-typo3/public/typo3/sysext/backend/Classes/Http/RequestHandler.php(94): TYPO3\\CMS\\Backend\\Http\\RouteDispatcher->dispatch(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#15 /var/www/newsite-typo3/public/typo3/sysext/extbase/Classes/Middleware/SignalSlotDeprecator.php(49): TYPO3\\CMS\\Backend\\Http\\RequestHandler->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#16 /var/www/newsite-typo3/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Extbase\\Middleware\\SignalSlotDeprecator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(TYPO3\\CMS\\Backend\\Http\\RequestHandler))\n#17 /var/www/newsite-typo3/public/typo3/sysext/backend/Classes/Middleware/SiteResolver.php(69): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#18 /var/www/newsite-typo3/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\SiteResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#19 /var/www/newsite-typo3/public/typo3/sysext/backend/Classes/Middleware/AdditionalResponseHeaders.php(41): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#20 /var/www/newsite-typo3/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\AdditionalResponseHeaders->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#21 /var/www/newsite-typo3/public/typo3/sysext/backend/Classes/Middleware/OutputCompression.php(47): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#22 /var/www/newsite-typo3/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\OutputCompression->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#23 /var/www/newsite-typo3/public/typo3/sysext/backend/Classes/Middleware/BackendUserAuthenticator.php(78): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#24 /var/www/newsite-typo3/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\BackendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#25 /var/www/newsite-typo3/public/typo3/sysext/backend/Classes/Middleware/BackendRouteInitialization.php(58): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#26 /var/www/newsite-typo3/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\BackendRouteInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#27 /var/www/newsite-typo3/public/typo3/sysext/backend/Classes/Middleware/ForcedHttpsBackendRedirector.php(55): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#28 /var/www/newsite-typo3/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\ForcedHttpsBackendRedirector->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#29 /var/www/newsite-typo3/public/typo3/sysext/backend/Classes/Middleware/LockedBackendGuard.php(73): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#30 /var/www/newsite-typo3/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\LockedBackendGuard->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#31 /var/www/newsite-typo3/public/typo3/sysext/core/Classes/Middleware/NormalizedParamsAttribute.php(45): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#32 /var/www/newsite-typo3/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Core\\Middleware\\NormalizedParamsAttribute->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#33 /var/www/newsite-typo3/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(78): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#34 /var/www/newsite-typo3/public/typo3/sysext/core/Classes/Http/AbstractApplication.php(85): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#35 /var/www/newsite-typo3/public/typo3/sysext/backend/Classes/Http/Application.php(63): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#36 /var/www/newsite-typo3/public/typo3/sysext/core/Classes/Http/AbstractApplication.php(97): TYPO3\\CMS\\Backend\\Http\\Application->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#37 /var/www/newsite-typo3/public/typo3/index.php(25): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()\n#38 /var/www/newsite-typo3/public/typo3/index.php(26): {closure}()\n#39 {main}"}

**Comment by liayn** [comment]
Which version/branch of extension_builder did you use?

**Comment by sergeyvo80** [comment]
> Which version/branch of extension_builder did you use?

extension_builder - v-10-compatibility
typo3 - 10.4.10

**Comment by liayn** [comment]
Please be a bit more verbose. What did you do when this error occurred? How can it be reproduced?

**Comment by sergeyvo80** [comment]
just add the module to typo3conf/ext then activate it Extension part then see an error in admin UI - The option "source" is required and must not be empty. 

I wrote the details above

**Comment by sergeyvo80** [comment]
I have renamed module to extension_builder_10 then a have renamed,
now i have renamed back to extension_builder, now i see Extension Builder in menu, but it this part returns error Class ExtensionBuilder\Controller\EBT\ExtensionBuilder\Controller\BuilderModuleControllerController does not exist. Reflection failed.

**Comment by liayn** [comment]
Now I understood it. You are talking about extension_builder itself and not about an extension it generated.
Okay, will take a look.

> Class ExtensionBuilder\Controller\EBT\ExtensionBuilder\Controller\BuilderModuleControllerController does not exist

You need to flush all caches via Install Tool

**Comment by liayn** [comment]
Can you please make sure you pulled the latest changes for the v-10 branch?
It works for me.

**Comment by rl-saen** [comment]
Hi,
I am currently seeing the same error when trying to access the admin interface with TYPO3 8.7.32.

Clearing the cache via the install tool worked for me.

**Comment by liayn** [comment]
Closing this due to lack of feedback.
