### ISSUE TITLE
Implement a property of type "Time" as DateTime Object instead of timestamp 

### ISSUE THREAD

**Issue by tgaertner** [FriendsOfTYPO3/extension_builder#336]
**Is your feature request related to a problem? Please describe.**
Problem one is that its not streamline with property "Date" - > that's an DateTime
Problem two is, it's not consistent in the database, bacause dafult "time()" produces a full timestamp, but eval 'time' (if field was edited) produces a shortened timestamp.

**Describe the solution you'd like**
I would change the Extbase property to an DateTime, change DB filed to "Time" (instead of int) and change TCA to 

```
'config' => [
                'dbType' => 'time',
                'type' => 'input',
                'renderType' => 'inputDateTime',
                'size' => 4,
                'eval' => 'time,null',
                'default' => ''
            ]
```

**Describe alternatives you've considered**
Or we should add a second option to give the choice how the property should be set up (like its done with DateTime).

**Comment by nicodh** [comment]
If you could make a PR it would be appreciated!

**Comment by tgaertner** [comment]
I think I can - have to dig into the code a bit more. Before starting with that I wanted to have a feedback if the change would make sense. So thanks for the quick answer, I see if I can figure out how to implement that and will make a PR.

**Comment by tgaertner** [comment]
https://github.com/FriendsOfTYPO3/extension_builder/pull/338

**Comment by tgaertner** [comment]
If you think this is ok, I can also do it for "time with seconds"

**Comment by simonschaufi** [comment]
> If you think this is ok, I can also do it for "time with seconds"

@tgaertner yes, we would appreaciate that!
