### ISSUE TITLE
Backend module default template layout produce jQuery Errors in TYPO3 V10

### ISSUE THREAD

**Issue by Treedent** [FriendsOfTYPO3/extension_builder#337]
**Describe the bug**
Using Backend Layouts Default.html for a backend Module produce a JavaScipt error :
Uncaught TypeError: e is null in RegularEvent.js

**To Reproduce**
Generate a new Backend module, install it and test it.

**TYPO3 Version**
10.4.12

**Extension Builder Version:**
Git-branch v10-compatibility

Removing the "t3js-module-docheader" class in the main div seems to correct the bug...

**Comment by simonschaufi** [comment]
@Treedent Thank you for your bug report but if you know how to fix it already, why don't you create a pull request? That would be awesome!

**Comment by liayn** [comment]
The Core still uses this code for the BE modules:
```
<div class="module-docheader t3js-module-docheader">
    <div class="module-docheader-bar module-docheader-bar-buttons t3js-module-docheader-bar t3js-module-docheader-bar-buttons">
...
    </div>
</div>
<div class="module-body t3js-module-body">
</div>
```

**Comment by liayn** [comment]
There is the `<be:moduleLayout>` viewhelper since v9, which should probably be used
