### ISSUE TITLE
Will not save correctly the extension unter  TYPO3 9

### ISSUE THREAD

**Issue by Padina14** [FriendsOfTYPO3/extension_builder#339]
https://stackoverflow.com/questions/65578439/typo3-9-5-extension-builder-throws-exception

**Comment by Padina14** [comment]
I tried to build a Extension with one Modell. (allowed list and show actions) and some entries for a frontend-plugin. 

After commenting the lins 58-69 in EBT\ExtensionBuilder\Parser\Visitor\ReplaceVisitor, the extention builder build the missing controller.  I am currently not sure, that the extension will work.

**Comment by simonschaufi** [comment]
Please add a screenshot so we know what you are doing

**Comment by Padina14** [comment]
After commenting the line abowe, the error was not reproducable.

I install the extensionbuilder newly with the composer. (ext_builder: 9.10.3). The error seems to come up only with the new installed extension
![Bildschirmfoto 2021-01-13 um 13 33 03](https://user-images.githubusercontent.com/63228213/104453047-23e2dd80-55a4-11eb-8d50-3325944cdb21.png)
.

**Comment by Padina14** [comment]
With my comment abbove the Extension build this controller. It may be a hint for the bug. 
Where comes the `domainObjectRepository` from?

![Bildschirmfoto 2021-01-13 um 13 36 43](https://user-images.githubusercontent.com/63228213/104453331-8c31bf00-55a4-11eb-9bdd-91011d9d2d8a.png)

**Comment by simonschaufi** [comment]
did you check the checkbox aggregate root? That is very important.

**Comment by Padina14** [comment]
That checkbox is activated.
![Bildschirmfoto 2021-01-13 um 16 40 46](https://user-images.githubusercontent.com/63228213/104474300-294d2180-55be-11eb-9e50-9454a7f8540f.png)
![Bildschirmfoto 2021-01-13 um 16 38 59](https://user-images.githubusercontent.com/63228213/104474311-2baf7b80-55be-11eb-86e3-8d0a2aa927e8.png)
![Bildschirmfoto 2021-01-13 um 16 38 14](https://user-images.githubusercontent.com/63228213/104474314-2c481200-55be-11eb-930e-242a115dff8f.png)

**Comment by FurtFan86** [comment]
Hello, I probably have exactly the same problem. A workaround: install TYPO3 and the extension builder without composer. So I could save the extension.

**Comment by schams-net** [comment]
I managed to reproduce the issue several times now. These are the steps I did:

https://user-images.githubusercontent.com/3617721/105619339-b6f20200-5e45-11eb-97fc-e14b82693ce4.mp4

I don't think that it matters if you create a frontend plugin as shown in the video or not. I am also not sure if the order of how components are installed is relevant (for example: I installed TYPO3, then the Extension Builder, before accessing the BE for the first time).

As I didn't have problems with the same environment (and its setup) before, I suspect that the issue could be related to newer versions of packages that are installed during the installation.

In general:

- Composer version 1.10.9
- PHP version 7.3.19
- TYPO3 version 9.5.24

**Comment by marble** [comment]
See also https://github.com/FriendsOfTYPO3/extension_builder/issues/250
Can confirm: I'm running into this as well.

**Comment by liayn** [comment]
Is this reproducable in v10 as well? (v10-branch of the extension)
Note: I(/we) currently only focus on v10 support.

**Comment by marble** [comment]
> Is this reproducable in v10 as well? (v10-branch of the extension)
I'll try that later. As v10 is what I'm heading at anyway.

**Comment by marble** [comment]
The above error of THIS issue DID NOT show up in a try with v10.
However I ran into https://github.com/FriendsOfTYPO3/extension_builder/issues/341 The procedure is given there.

**Comment by liayn** [comment]
Thanks a lot @marble!

I will therefore not pay attention to this issue for the time being.
Anyone else is of course free to pick it up.
Create a PR against the master-branch then please.

**Comment by schams-net** [comment]
The problem originates from a new(er) version of [nikic/php-parser](https://packagist.org/packages/nikic/php-parser). As of today, TYPO3 v9.5.24 pulls nikic/php-parser v4.10. Older versions of this package seem to work, for example v4.3.0.

Workaround:
```bash
composer require nikic/php-parser:4.3.0
```
It would be great if someone could confirm this.

**Comment by liayn** [comment]
TYPO3 Core v9 as zip ships php-parser v4.4.0

**Comment by schams-net** [comment]
> TYPO3 Core v9 as zip ships php-parser v4.4.0

The issue does not occur with TYPO3 v9 as a ZIP or .tar.gz source package (at least up to v9.5.24). However, if you replace the `typo3_src-9.5.24/vendor/nikic/php-parser/` directory with an up-to-date version of the library — for example v4.10 — the same error pops up (dump autoload and clear caches of course :-)

**Comment by liayn** [comment]
So pls check the v10 branch for the fix for php-parser (there must be one, because v10 ships v4.10.4 currently) and backport it. Thanks.
