### ISSUE TITLE
uploads/tx_extensionbuilder/backups/ folder is missing

### ISSUE THREAD

**Issue by marble** [FriendsOfTYPO3/extension_builder#341]
1. Do a fresh DDEV v10 TYPO3 install
2. Add extension: `composer require friendsoftypo3/extension-builder:dev-v10-compatibility`
3. See this on the screen `- Installing friendsoftypo3/extension-builder (dev-v10-compatibility 837d249)`
4. In the backend the extension is already installed.
5. Use extension-builder to create extension with a model
6. Try to save: ![image](https://user-images.githubusercontent.com/307057/106736720-1aceb480-6616-11eb-96fd-35f158bbaad6.png)

Initial saving was possible.
TYPO3 is in `/var/www/html/public/`

Creating `/var/www/html/uploads/tx_extensionbuilder/backups/` manually DOES fix the problem.

**Comment by liayn** [comment]
Thanks. Good catch.

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88525-RemoveCreateDirsDirectiveOfExtensionInstallationEm_confphp.html

We need to create this directory in a different place and manually within the code.

**Comment by liayn** [comment]
#298 already removed this functionality for the generated extensions

**Comment by nicodh** [comment]
what is best practice for extension folders since the uploads folder is not used any more?

**Comment by liayn** [comment]
There is none as far as I know. Files within records use FAL and everything else is totally up to the developer what has to happen with files.

**Comment by simonschaufi** [comment]
I would say the `var` folder is the new storage ;)

**Comment by liayn** [comment]
> these kind of things

What are those things?

**Comment by DavidBruchmann** [comment]
@nicodh  either usage of typo3temp with the danger that it's lost if the folder is emptied or not used i.e. on server relocation, or alternatively a special folder in storage `1:` which is most often the folder `fileadmin`. The folder in fileadmin had to be defined new probably, I've doubts that special folders there have names that are really fitting.

**Comment by simonschaufi** [comment]
I'm against FAL because FAL doesn't need to know about the extension.

> Files that are not imported into FAL and not "temporary" like in typo3temp. `var` is more a permanent storage

**Comment by liayn** [comment]
Extensions *MUST NEVER* be stored inside a FAL storage! This causes only big mess.

I see no practical use case where an extension might handle uploads, which are stored in a folder (eg `var`) which is inaccessible for BE users.

**Comment by DavidBruchmann** [comment]
I suppose you wouldn't save the folder `importexport` in fileadmin too.
```
fileadmin
    _migrated
    __processed__
    user_upload
        _temp_
            importexport
```

**Comment by liayn** [comment]
> _migrated

Is a very legacy folder created during migration from pre-FAL times to FAL. This folder does not exist on new installations.

> importexport

There is no other place than FAL storages where BE users can upload files to. This is true for `ext:impexp` too, hence those files reside there.

**Comment by simonschaufi** [comment]
I think there are some misunderstandings right now. What are we actually talking about? I think we are talking about a backup folder and not an upload folder and a backup folder can be created in `var` imho.

**Comment by liayn** [comment]
Right, I'm sorry, I got a bit off-track with the other ticket.

The backups can be stored in `var`, yes.
