### ISSUE TITLE
Saving extension not working

### ISSUE THREAD

**Issue by daviian** [FriendsOfTYPO3/extension_builder#35]
When saving an extension in extension builder an error occurs.

Error Message:
Uncaught TYPO3 Exception: Call to undefined method TYPO3\CMS\Extbase\Configuration\ConfigurationManager::parseRequest() | Error thrown in file /var/www/html/typo3conf/ext/extension_builder/Classes/Controller/BuilderModuleController.php in line 172.

**Comment by daviian** [comment]
Ok sorry, I was too quick opening a new issue instead of taking a more precise look into my git log.
Already fixed with #32

**Comment by daviian** [comment]
After pulling the latest commit a new error arises.

Uncaught TYPO3 Exception: Call to a member function getExtensionSettings() on null | Error thrown in file 
/var/www/html/typo3conf/ext/extension_builder/Classes/Service/ExtensionSchemaBuilder.php in line 279.

**Comment by nicodh** [comment]
Please clear all caches. There is a class info cache which keeps the class reflection infos...

**Comment by daviian** [comment]
Ok thanks, that helped out ;-)
