### ISSUE TITLE
Selection of folder don't work, create EXT in wrong folder. 

### ISSUE THREAD

**Issue by olegkarun** [FriendsOfTYPO3/extension_builder#351]
**Describe the bug**
After install extension_builder cant create the first extension - a selection of extension root folder don't work

**To Reproduce**
1. composer require friendsoftypo3/extension-builder:dev-v10-compatibility
```
        'extension_builder' => [
            'backupDir' => 'uploads/tx_extensionbuilder/backups',
            'backupExtension' => '1',
            'enableRoundtrip' => '1',
        ], 
```

2. Click on the backend interface and create a new EXT with minimal settings
3. See an error 

**Expected behavior**
Crete new extension in the folder  typo3conf/ext/

**Screenshots**
![ext_builder](https://user-images.githubusercontent.com/3882942/107760397-56fac700-6d32-11eb-8648-ae1821c8c28c.jpg)
![ext_builder2](https://user-images.githubusercontent.com/3882942/107760406-5b26e480-6d32-11eb-8a27-6447c3965f4e.jpg)

**TYPO3 Version**
10.4.12

**Extension Builder Version:**
https://packagist.org/packages/friendsoftypo3/extension-builder#dev-v10-compatibility
816a4bd

**Comment by liayn** [comment]
This is obviously not a bug.

The folder selection is empty, because you did not create the requirements to use extension_builder *within* a composer-based installation.

The documentation is available already here https://github.com/FriendsOfTYPO3/extension_builder/blob/b1b4853e6bde7c74f385d9700031bbc06eb5698d/Documentation/User/Index.rst#composer-mode

**Comment by olegkarun** [comment]
@liayn I'm trying different ways.. like added in my root composer.json 

```
    "repositories": [
        {
            "type": "path",
            "url": "public/typo3conf/ext"
        }
    ],

```
I need a simple next structure

web-root
 - composer.json 
 - public
 -  - typo3conf
 -  -  - ext
 -  - - - myext
 - vendor

As I understand, the local repository in composer.json need just when you can not work directly in the `typo3conf/ext` folder and you can store your new package (ext) in another directory, and extension_builder will create the symlink from your custom folder to `typo3conf/ext`? If I'm right, how I can set up the ext_builder in a simple way - to work directly in TYPO3 ext folder without symlinks and other staff? 

@liayn Many thx for the advice. Sorry for the stuped question, trying to figure out this staff 


Currently, with the settings in composer.json, I still have this message 

![ext_builder3](https://user-images.githubusercontent.com/3882942/107783918-7bb36680-6d53-11eb-9da5-5a0912cbb1d9.jpg)

But can't open some old EXT, just cant save 
![ext_builder4](https://user-images.githubusercontent.com/3882942/107784027-a43b6080-6d53-11eb-9ad9-bd2490eab327.jpg)

**Comment by liayn** [comment]
> "url": "public/typo3conf/ext"

I am totally certain that this will cause pure mess!

Better go for this structure:

```
web-root
 - composer.json 
 - packages
 - public
 -  - typo3conf
 -  -  - ext
 - vendor
```

and composer.json

```
    "repositories": [
        {
            "type": "path",
            "url": "packages/"
        }
    ],
```

**Reasoning:**

The "composer installers" package of TYPO3 kicks in when `composer install` is run and will automatically take care of moving extensions into `typo3conf/ext` or symlink them there.
If you declare `typo3conf/ext` as the path-local repository, something will for sure be overwritten or at least not working.

**Comment by olegkarun** [comment]
@liayn Thx for your advice. But how should I migrate my old project EXT in this case. To do setup the local path and move to the new `packages` folder in the project root? I'm right?

**Comment by liayn** [comment]
Not sure what "old project EXT" means?

Does it already have a valid `composer.json` file?
What makes it "old"?

**Comment by saenglert** [comment]
I am running into the same error at the moment with an extension that was originally created in LTS 7 (as far as I know). I guess that's what @olegkarun means when asking about migrating an old ext: Can one simply save an extension from pre-LTS 10 with the new version of EB?

![grafik](https://user-images.githubusercontent.com/6491588/108814997-08f88580-75b4-11eb-9487-a15053da445e.png)

**Comment by saenglert** [comment]
Got it figured out:

No, it is not possible to simply save a pre update extension.
The error occurs because `"storagePath": "\/some\/folder\/"` is not set which is required for the saving process.

(Maybe) possible solution: Use the folder that is currently selected in EB to save to in case `storagePath` is not set.

**Comment by olegkarun** [comment]
@saenglert I added in my root composer,json
```
{
    "repositories": [       
        {
            "type": "path",
            "url": "./packages/*"
        }
    ],

    "name": "typo3/website",
   ```
  "require": {
    "myvendor/newext": "@dev",
  ...
```

and create folder `packages`

its work for me this way

Some more information I found here https://docs.typo3.org/m/typo3/guide-installation/master/en-us/MigrateToComposer/BestPractices.html

**Comment by Gernott** [comment]
I found the main problem:
If you load an extension from an old TYPO3, this line is missing in ExtensionBuilder.json:
`"storagePath": "\/var\/www\/html\/extensions\/",`
If I add this line and adapt the path to my needs, it works without Error 500.

**Comment by simonschaufi** [comment]
I guess there is nothing to fix here. If I'm wrong, please give feedback.

**Comment by Gernott** [comment]
You simply have to add this line to ExtensionBuilder.json, if it is missing:
 "storagePath": "\/var\/www\/html\/extensions\/",
Then it is possible, to load Extensions from older ExtensionBuilder Versions.
