### ISSUE TITLE
Annotations are not updated

### ISSUE THREAD

**Issue by saenglert** [FriendsOfTYPO3/extension_builder#358]
**Describe the bug**
When saving an extension that was created before [the commit that updated annotations](https://github.com/FriendsOfTYPO3/extension_builder/commit/ad963ddbfb7b28926ae31cad84272da96cc9dc74), the deprecated and now removed annotations are still being used instead of being updated

**To Reproduce**
1. Open an extension which was created before said date
2. Click save
3. Check models

**Expected behavior**
Annotations should be updated to the most recent standard

**TYPO3 Version**
LTS 10

**Extension Builder Version:**
v-10-compatibility branch

**Additional context**
I guess it's easy enough to just use search&replace on the extension. So if an automatic solution would cost a lot of time it's imho not worth the effort.

**Comment by simonschaufi** [comment]
For those kind of things i would prefer to use rector instead of the extension builder as the extension builder is not a code migration tool.
