### ISSUE TITLE
Adjust generated tests and tests of ext itself to CMS 8 testing framework

### ISSUE THREAD

**Issue by liayn** [FriendsOfTYPO3/extension_builder#36]

**Comment by nicodh** [comment]
Any idea how to work around this (happens only with PHP 7.1):

>  include(): file:// wrapper is disabled in the server configuration in /home/travis/build/FriendsOfTYPO3/extension_builder/.Build/vendor/composer/ClassLoader.php on line 444

**Comment by liayn** [comment]
`allow_url_include` option of PHP
