### ISSUE TITLE
About section points to old ext. docs

### ISSUE THREAD

**Issue by AMartinNo1** [FriendsOfTYPO3/extension_builder#362]
https://docs.typo3.org/typo3cms/extensions/extension_builder/stable/Index.html

vs.

https://docs.typo3.org/p/friendsoftypo3/extension-builder/master/en-us/Index.html

------

Acceptance Criteria:
- [x] The link in the About section points to https://docs.typo3.org/p/friendsoftypo3/extension-builder/master/en-us/Index.html

**Comment by simonschaufi** [comment]
fixed in https://github.com/FriendsOfTYPO3/extension_builder/commit/576127ae527c6df8278f79cf583764b501871408
