### ISSUE TITLE
Domain modeller doesn't create full tables

### ISSUE THREAD

**Issue by bytesinmotion** [FriendsOfTYPO3/extension_builder#367]
I just started a new project and used the latest v10-master as base.
I created several tables and the resulting ext_tables.sql didn't contain any default fields like uid, language fields and others.

To be sure I created another new test-extension with just 1 table and 1 field. Selected multilanguage field but this is what I get in the ext_tables.sql:

CREATE TABLE tx_jobfinder2_domain_model_branchen (

	title varchar(255) DEFAULT '' NOT NULL

);

**Comment by liayn** [comment]
Since TYPO3 v9 this is not necessary anymore, the Core creates those fields implied by TCA|ctrl section automatically

**Comment by bytesinmotion** [comment]
Oh sorry my fault. First time I'm using it under v10 and I created a huge set of tables with no detail fields yet and then got scared that something is not working with the builder when I saved the first two tables with fields :)
Sorry again
