### ISSUE TITLE
Modified ext_emconf File will be overwritten

### ISSUE THREAD

**Issue by vkemeter** [FriendsOfTYPO3/extension_builder#37]
hi,

if you use a 7.6 without composer and you need to add autoloading to the ext_emconf file, it will be overwritten within the next save from the extension_builder.

as long as it is possible to use typo3 without composer and you need autoloading stuff, the file should have the same "token" or something like the other files to make that possible.

thx.

**Comment by nicodh** [comment]
I think you don't need a token in that file once it is generated. Just configure the overwriteSettings to 'keep' in the Configuration/ExtensionBuilder/settings.yaml file

**Comment by liayn** [comment]
@vkemeter Even if you do not use composer in the installation I would always add a composer.json to all extensions, no matter if public or not.
We only add autoloading info there and not in emconf.
This way the extension has maximum compatibility in the CMS 7 & 8 world, with our w/o composer.

**Comment by vkemeter** [comment]
@liayn : yeah, i know. but that is not the point ;) if the instance does not have any composer foo, you need to register the autoloading somehow. 

@nicodh : i did not found a way to put in the emconf file in the settings.yaml file, or is it possible to put any file in there for "skipping"?

thx. volker.

**Comment by liayn** [comment]
>  if the instance does not have any composer foo, you need to register the autoloading somehow

I don't know what you mean.
Even if the instance is not in composer mode, the extension manager still reads the autoloading info from the composer.json files of extensions!

**Comment by vkemeter** [comment]
even in a 7.6 instance? didn't know that. ill try that ;)

**Comment by liayn** [comment]
doing this "since years" (tm) ;-)

**Comment by nicodh** [comment]
To keep your ext_emconf.php just add a line:
  ext_emconf.php: keep
below the line "overwriteSettings:" in Configuration/ExtensionBuilder/settings.yaml
Did you try that?

**Comment by nicodh** [comment]
Can we close this?
