### ISSUE TITLE
incorrect escaping of quotes

### ISSUE THREAD

**Issue by Gernott** [FriendsOfTYPO3/extension_builder#38]
If using 'Extend existing model class' - e.g. with \TYPO3\CMS\Extbase\Domain\Model\FrontendUser, the generated code in TCA/Overrides/fe_users.php looks like:

`if (isset($GLOBALS[&#039;TCA&#039;][&#039;fe_users&#039;][&#039;types&#039;][&#039;0&#039;][&#039;showitem&#039;])) {`

All quotes are HTML-encoded. Temporary solution for developers: Search&Replace this:
`&#039;`
with this:
'

**Comment by liayn** [comment]
@Gernott Which version are you using? I suppose the one for CMS 8?

**Comment by Gernott** [comment]
Oh, yes, TYPO3 8 LTS and current master from here.

**Comment by floriankuehl** [comment]
Same quirk happens in the CodeTemplates for TCA (PropertiesDefinition.phpt) 
and in the Generator for ext_tables.sql.
I tried to render the Partial PropertiesDefinition.phpt inline with f:format.raw, but it does not help.

Maybe something changed in the StandaloneFluidTemplate in 8.7.

Quick Fix:
Search and Replace
  &amp;    to     &
  &#039;   to     '
  &gt;       to      >

**Comment by liayn** [comment]
can you please try adding a `{escaping off}` to the beginning of all template files?

_Background: Fluid Standalone does html escaping on all formats by default, not only for .html. This is why .phpt is getting escaped as well._

**Comment by floriankuehl** [comment]
Works like a charm ! Thank you Liayn

**Comment by liayn** [comment]
okay, then pls create a PR.

**Comment by nicodh** [comment]
Should be fixed with 3969038d1c29

**Comment by Gernott** [comment]
Sorry for commenting a closed issue, but I have a further question:
The bug is in a PHP file in /Configuration/TCA/Overrides/fe_users.php, not in a HTML file. So I cannot add a fluid Tag to PHP.
Do I understand something wrong? Or should I create a new issue?

**Comment by nicodh** [comment]
fe_users.php is the generated file. The fluid tag should go to the template of that file, not to the file itself. Overrides/fe_users.php  is based on TCA/Overrides/tableName.phpt and it's partials...

**Comment by Gernott** [comment]
I don't have a Fluid-Template for this TCA Type.
I don't understand why a Fluid Tag in a HTML file should correct the PHP code of the Extensionbuilder?
There is something new for me: I have never heard from .phpt files...? Is there any documentation for it?
Or do you mean, I should create the file /Configuration/TCA/Overrides/fe_users.phpt, only with the fluid tag? Sorry, I'm confused ;)
