### ISSUE TITLE
Error while saving a new Extension

### ISSUE THREAD

**Issue by hxtom68** [FriendsOfTYPO3/extension_builder#380]
we got this error when we save a new minimal extension:

Extension could not be saved: PHP Warning: symlink(): File exists in /app/public/typo3conf/ext/extension_builder/Classes/Controller/BuilderModuleController.php line 297

TYPO3 V10.4.14
composer mode

Thanks

**Comment by simonschaufi** [comment]
Closing this as with proper composer.json path it works
