### ISSUE TITLE
New Extension can't be saved

### ISSUE THREAD

**Issue by FUTC-Coding** [FriendsOfTYPO3/extension_builder#382]
I created a new extension and get this error when saving `Extension could not be saved: Could not create file, error: PHP Warning: fopen(/key/.gitignore): failed to open stream: No such file or directory in /var/www/html/public/typo3/sysext/core/Classes/Utility/GeneralUtility.php line 1834`

**Expected behavior**
Saving the extension

**TYPO3 Version**
Typo3 v10 with composer. Though I think I still need to add the local repo to the composer file but this issue seems unrelated.

**Extension Builder Version:**
Git-branch

**Comment by liayn** [comment]
This is totally related.

As EB does not know where to save the extension to, it fails to generate a correct path for the `.gitignore` file.

**Comment by FUTC-Coding** [comment]
Oh then I'm sorry for mislabeling this issue. How can I add it as a local repo to composer though? I wasn't able to find anything concerning this in the documentation.

**Comment by FUTC-Coding** [comment]
Thanks, I got it running after some trial and error.
