### ISSUE TITLE
missing quotes for 'uploadfolder' in ext_emconf.php

### ISSUE THREAD

**Issue by Padina14** [FriendsOfTYPO3/extension_builder#383]
**Describe the bug**
See screenshot. I only want to build a skeleton for an extension.

**To Reproduce**
add a new Steps to reproduce the behavior:
1. build a simple extension with title, vendorname, name, title author-data (NO modell, no Plugins) 
2. Save the extensionSave
3. go to extensionmanager in TYPO3

**Expected behavior**
No exception 

**Screenshots**
![Bildschirmfoto 2021-05-12 um 10 46 42](https://user-images.githubusercontent.com/63228213/117947296-5b725400-b310-11eb-81e8-13d2969f997f.png)

**TYPO3 Version**
TYPO3 9.5

**Extension Builder Version:**
---

**Additional context**

**Comment by Padina14** [comment]
Sorry Extensionbuilder version 'version' => '9.10.3',

**Comment by liayn** [comment]
Please use the latest version from git (master-branch), which includes my fix.
