### ISSUE TITLE
TypeError in AnyToManyRelation::setMaxItems while saving extension

### ISSUE THREAD

**Issue by benwick** [FriendsOfTYPO3/extension_builder#388]
**Describe the bug**
The setMaxItems method in [AnyToManyRelation](https://github.com/FriendsOfTYPO3/extension_builder/blob/8cac1b0204190d095c20e9b2092fd75ba4d0d3db/Classes/Domain/Model/DomainObject/Relation/AnyToManyRelation.php#L109) expects int, string is given. String is given because the maxItems value in the ExtensionBuilder.json are/were saved as string. This leads to a type errror while saving the extension.

**To Reproduce**
I have created a domain model with a file field and set maxItems to 20.

**Expected behavior**
I can save the extension without at type error

**TYPO3 Version**
10.4.15

**Extension Builder Version:**
Current Master-Dev.

**Additional context**
Bug originated by [declaring stric type](https://github.com/FriendsOfTYPO3/extension_builder/blame/8cac1b0204190d095c20e9b2092fd75ba4d0d3db/Classes/Domain/Model/DomainObject/Relation/AnyToManyRelation.php#L3).

**Comment by simonschaufi** [comment]
Thanx for the bug report. It is fixed now.
