### ISSUE TITLE
Custom Action should also create a template file

### ISSUE THREAD

**Issue by georgringer** [FriendsOfTYPO3/extension_builder#399]
If a custom action is created, it would be nice if an according template would be created. this can be of course also empty but would be convenient. 

IMO if no template is provided, also an exception is thrown

![image](https://user-images.githubusercontent.com/1905663/121492161-ecebe900-c9d6-11eb-9e6c-7594f28b17cc.png)

**Comment by simonschaufi** [comment]
I agree but it could also be an action that does a redirect in the end

**Comment by georgringer** [comment]
yes of course but in most use cases this will be a template
