### ISSUE TITLE
Bogus relation possible

### ISSUE THREAD

**Issue by georgringer** [FriendsOfTYPO3/extension_builder#400]
The UI allows a bogus relation, see screenshot

![image](https://user-images.githubusercontent.com/1905663/121520142-dd7a9900-c9f2-11eb-83c6-6a89acc36654.png)

I know this won't work but my students just did that and maybe it can be disabled?

**Comment by simonschaufi** [comment]
I'm aware of this possibility but the wireit library is super complicated to understand

**Comment by DavidBruchmann** [comment]
could this connection reflect a biderectional m:m connection?

**Comment by simonschaufi** [comment]
I tried to see see if true m:n relations are actually possible and noticed that they are not! There is no bi-directional relationship created in both models but just in one. Like David suggested, one would expect to actually create a bi-directional relationship with these kind of wires. Let me see if I can fix that....

**Comment by simonschaufi** [comment]
Duplicate to #295

**Comment by simonschaufi** [comment]
Fixed! It was actually way easier than I thought ;)
