### ISSUE TITLE
Bogus database tables possible

### ISSUE THREAD

**Issue by georgringer** [FriendsOfTYPO3/extension_builder#401]
My students just did some nice extension which lead to a DBAL exception because of sql like this
```sql
CREATE TABLE tx_dummy_domain_model_traube (
	sorte int(11) unsigned DEFAULT '0' NOT NULL,
	sorte varchar(255) DEFAULT '' NOT NULL
);
```

Checkout the screenshot how this can be reproduced

![image](https://user-images.githubusercontent.com/1905663/121521221-16673d80-c9f4-11eb-8565-fef2b563330e.png)

I *know* it shouldn't be that way but IMO there must be a warning if a parent DB field is created which got a name which is not unique anymore

**Comment by simonschaufi** [comment]
Thanks for the screenshot, that helped a lot! It is an edge case that only appears in 1:n relation with inline render type
