### ISSUE TITLE
[TASK] Make property type *Select list* configurable

### ISSUE THREAD

**Issue by jonakieling** [FriendsOfTYPO3/extension_builder#413]
Currently the *Select list* property type defaults to an integer in the database and a single item. Unfortunately this overrides manuell adjustments to the items config.

Proposition: Let users configure the items of a *Select list* via the Editor. I am thinking of a text field with comma or pipe seperated lines. This way all features from [TCA Documention](https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/ColumnsConfig/Type/selectSingle.html#items) can be covered.
Something like this:
```text
    LLL:EXT:cms/locallang_ttc.php:k1|0|EXT:myext/Resources/Public/selicons/k1.gif|Optional Description
    LLL:EXT:cms/locallang_ttc.php:k2|1|tx-myext-selicons-k2
    LLL:EXT:cms/locallang_ttc.php:k3|2|tx-myext-selicons-k3
```

Addition: Depending on the value of items the database column type could be derived.

-------------

- [x] input for "where-clause"
- [x] maxItems must not be a default "0" -> with maxItems => 0, no items are stored

**Comment by PKuhlmay** [comment]
https://docs.typo3.org/m/typo3/reference-tca/12.4/en-us/ColumnsConfig/Type/Select/Index.html

**Comment by PKuhlmay** [comment]
I made a concept inside the commit https://github.com/FriendsOfTYPO3/extension_builder/commit/b9d681dcb957d1d5e1146586697a247cfe26f57e where it is possible to add the values for the select box. It is currently a textbox where you can set the values like "Label|value;Label two|valuetwo". I think it is not ideal, but it is still a concept.
It is only available for alpha-branch for TYPO3 12 at the moment, as the GUI for TYPO3 11 is an old framework from Yahoo. At this point I a not really sure if I will backport this commit to TYPO3 11.

**Comment by PKuhlmay** [comment]
Fixed in https://github.com/FriendsOfTYPO3/extension_builder/commit/bb84d92495f904c3f2641ffa02b96aaa0cde0e71

**Comment by PKuhlmay** [comment]
This could also have an input field for a "where-clause". Then only the matching records will be displayed in the select box.
Example: show only the values from the database XY where the field "isTrue" is really true. The other values from the database are then not shown inside the select box.
