### ISSUE TITLE
Missing template for custom backend actions

### ISSUE THREAD

**Issue by marcelwiegand** [FriendsOfTYPO3/extension_builder#418]
**Describe the bug**
When you create a backend module that points to a custom action it will try to generate a template for it and fail.
I think this is related to this commit https://github.com/FriendsOfTYPO3/extension_builder/commit/d6e16ddeff4294702cab701e0270964a99351965
which adds a custom.htmlt for custom frontend actions but doesn't include a template for custom backend actions.

**Screenshots**
![image](https://user-images.githubusercontent.com/44807370/124913592-98e11e00-dfef-11eb-9df0-4b8d0e31f0fd.png)

**Comment by simonschaufi** [comment]
Indeed, I probably forgot the backend module templates.

**Comment by simonschaufi** [comment]
fixed
