### ISSUE TITLE
Create boilerplate files (stubs) via cli

### ISSUE THREAD

**Issue by simonschaufi** [FriendsOfTYPO3/extension_builder#431]
Flow has it, Laravel has it but only TYPO3 misses it: Creating boilerplate files (stubs) via cli:

- https://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartII/Kickstart.html#kickstart-the-package
- https://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartII/Kickstart.html#kickstart-controllers
- https://laravel.com/docs/8.x/controllers

This could be part of the extension builder but also be a separate extension providing all the commands

**Comment by simonschaufi** [comment]
Implemented with https://github.com/b13/make 🥳

**Comment by alexander-nitsche** [comment]
We should advise the make extension in our introduction section "What does it not do?" as soon as we can clearly describe its use cases. Waiting for https://github.com/b13/make/issues/11 to be resolved.
