### ISSUE TITLE
Generated unittests break with phpunit 9 (required by the v10 testingframework)

### ISSUE THREAD

**Issue by cypelt** [FriendsOfTYPO3/extension_builder#436]
**Describe the bug**
Testing attributes has been removed from phpunit https://github.com/sebastianbergmann/phpunit/issues/3339#issuecomment-428843322
calls like self::assertAttributeEquals break
**To Reproduce**
run the unit tests of setters generated by the extension builder
**Expected behavior**
do not generate broken unit tests.

**TYPO3 Version**
v10, phpunit 9
**Extension Builder Version:**
v10.0.1

**Additional context**
as [stated](https://github.com/sebastianbergmann/phpunit/issues/3339#issuecomment-445168829) in the thread, this is considered bad practice (protected/private attributes). So to test if the attribute has been set we need to check it via the "public api" which would be the getter.

**Comment by simonschaufi** [comment]
Could you create a PR that fixes the wrong behavior?
