### ISSUE TITLE
Allow extensions prefixed with "user_"

### ISSUE THREAD

**Issue by gianstraf** [FriendsOfTYPO3/extension_builder#44]
Hi,
in past versions (and in last), is not allowed save extensions with prefix 'user_'. Much times, we work on specific projects and we've the need of write a cutom specific project extension. We start to create extension with exension_builder,but we are forced to modify extension, to allow to save new extension with prefix user_*. Will be possible allow prefix 'user_*' in this and in the next releases ?

Thank you,
Gianluca

**Comment by liayn** [comment]
Can you please explain why you need this `user_` prefix?

**Comment by gianstraf** [comment]
According with [TYPO3 convention](https://docs.typo3.org/typo3cms/CoreApiReference/ExtensionArchitecture/ExtensionKey/Index.html), we use prefix 'user_' for local estensions specific for a project.

> Project specific extensions (not generally usable or shareable): Select any name you like and prepend it "user_" (which is the only allowed use of a key starting with "u"). This prefix denotes that this extension is a local one which does not come from the central TYPO3 Extension Repository or is ever intended to be shared. Probably this is an "adhoc" extension you have made for some special occasion.

**Comment by liayn** [comment]
I brought this documentation part to discussion within the TYPO3 Core Team. It looks like that this is totally outdated and we currently look into simply removing this paragraph entirely.
The Core code does not enforce this in any place.

**Comment by gianstraf** [comment]
Ok. In my experience I know that 'user_' prefix convention exists since the older TYPO3 versions. Will it no longer be valid? I hope the TYPO3 Core Team will explain this choice.

Thank you,
Gianluca

**Comment by liayn** [comment]
Any extension key is valid. There is no special treatment for `user_` except if you add old pibase plugins, which is not an issue here for extbase.

So to put it simple: the ext key does not matter, like, at all. :-)
(not so much explanation necessary therefore)

**Comment by gianstraf** [comment]
Yes, today prefix 'user_' is only a convention right. 
Then, I think that this code should be changed about the constraint  on prefix 'user_'. Will be :) ?

```
 /**
     * @author Rens Admiraal
     * @param string $key
     * @return void
     * @throws ExtensionException
     */
    private function validateExtensionKey($key)
    {
          // [...]
         /**
         * Reserved prefixes
         * The key must not being with one of the following prefixes: tx,u,user_,pages,tt_,sys_,ts_language_,csh_
         */
        if (preg_match('/^(tx_|u_|user_|pages_|tt_|sys_|ts_language_|csh_)/', $key)) {
            $this->validationResult['errors'][] = new ExtensionException(
                'Illegal extension key prefix', self::ERROR_EXTKEY_ILLEGAL_PREFIX);
        }
}
```

**Comment by liayn** [comment]
I would kick this completely.

@nicodh What do you think?

**Comment by nicodh** [comment]
+1
