### ISSUE TITLE
Model object property name: Cannot use arrow keys

### ISSUE THREAD

**Issue by cweiske** [FriendsOfTYPO3/extension_builder#46]
I cannot use the arrow keys to navigate inside a property's name field because some javascript always moves the cursor back to the end. This prevents me from fixing typos.
![2017-05-05 auswahl_002](https://cloud.githubusercontent.com/assets/59036/25739766/9b1c163a-3183-11e7-80a5-dca92a4ac298.png)

**Comment by liayn** [comment]
As far as I know this is "by design" of the underlying library to ensure correct user input.
Personally I dislike that too, but I learned to live with it ^^
