### ISSUE TITLE
mixed tab and space indentation in generated TCA file

### ISSUE THREAD

**Issue by cweiske** [FriendsOfTYPO3/extension_builder#47]
The generated TCA php files have both spaces and tabs mixed for indentation. This should be unified to spaces.

![2017-05-05 auswahl_003](https://cloud.githubusercontent.com/assets/59036/25739901/4d781de2-3184-11e7-8aab-c5b260bfd77b.png)

**Comment by nicodh** [comment]
Fixed in 7.6
