### ISSUE TITLE
Models that implements any interface will lead to type error while saving

### ISSUE THREAD

**Issue by benwick** [FriendsOfTYPO3/extension_builder#477]
**Describe the bug**
When a model implements any interface, `ClassObject::addInterfaceName` will lead to a type error, because its parameter should be string, but is fed an instance of `\PhpParser\Node\Name`.

**To Reproduce**
1. Create a model and save extension
2. Edit said model and let it implement any interface
3. Reopen Extension and save again

**Expected behavior**
Saving should work

**TYPO3 Version**
v10.4

**Extension Builder Version:**
v10.0.1

**Additional context**
Possible solution: Force `$interfaceNode` to string in [this line](https://github.com/FriendsOfTYPO3/extension_builder/blob/master/Classes/Parser/ClassFactory.php#L50).

**Comment by simonschaufi** [comment]
Thank you for that great bugreport. That was rally easy to reproduce and fix.
