### ISSUE TITLE
V11 dependens still on V10

### ISSUE THREAD

**Issue by hgalt** [FriendsOfTYPO3/extension_builder#506]
**Describe the bug**
In ext_emconf.php the depends still on V10 and not on V11

**TYPO3 Version**

**Extension Builder Version:**
V11 master

**Comment by hgalt** [comment]
Simon,
I have tested it again! In the ext_emconf.php the`depends  will be always reseted to 10.4.0-10.4.99
![grafik](https://user-images.githubusercontent.com/6670160/136649921-9530a8ca-8577-41c8-9bc4-f48fa1f36ce1.png)
This is a part of the ExtensionBuilder.json file.
It seem to be, that it is not updated in 11.0.0 for existing projects!

**Comment by simonschaufi** [comment]
Well, in that case open the left sidebar of the extension manager, there is a text box for all dependencies. You need to manually adjust that.

**Comment by hgalt** [comment]
Thanks, I did it. But should it be not happen automatically, if ExtensionBuildner is doing the modificatins or atleast give a warning?

**Comment by simonschaufi** [comment]
Extension Builder is not doing any magic. It could also be your extension is compatible with 10 and 11 at the same time thus no auto replacement.
