### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by develth** [FriendsOfTYPO3/extension_builder#509]
**Describe the bug**
Try to create a new Extension, starting with Basics, after frist Save ERROR:

``Extension could not be saved: PHP Warning: Undefined array key 500 in /var/www/public/typo3conf/ext/extension_builder/Classes/Controller/BuilderModuleController.php line 620``

**To Reproduce**
1. Open Extension Builder
2. Click on 'New Extension'
3. Fill in `Name`, `Vendor Name` and `Key`
3. Save

**Expected behavior**
Extension should be Saved

**Screenshots**
![Bildschirmfoto 2021-10-08 um 13 22 30](https://user-images.githubusercontent.com/3374563/136548316-d23ac7e1-9a3d-48d7-b668-0aa17495a140.png)

**TYPO3 Version 11.5**

**Extension Builder Version:**
composer, 11.0.0

**Comment by simonschaufi** [comment]
Could you downgrade to PHP 7.4 temporarily? Sorry that it's not yet working with PHP 8.
