### ISSUE TITLE
Create Fluid templates with xmlns namespaces

### ISSUE THREAD

**Issue by liayn** [FriendsOfTYPO3/extension_builder#52]
Use `xmlns:<namespace>` for all Fluid templates

**Comment by nicodh** [comment]
Is there an "official" xsd schemaLocation available for TYPO3 Fluid?
If I use 
`
<html data-namespace-typo3-fluid="true" xmlns:f="https://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers" xmlns:n="https://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers">
`
Phpstorm complains that the uri is not recognized...

**Comment by liayn** [comment]
No, there is no reachable url. You have to use the `https://typo3.org/ns/` part in order for Fluid to work.

**Comment by liayn** [comment]
Why do you declare the same namespace under to names?
```
xmlns:f="https://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers"
xmlns:n="https://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers"
```

**Comment by nicodh** [comment]
That was just a relict from my tests. But using
 `<html data-namespace-typo3-fluid="true" xmlns:f="https://typo3.org/ns/">`
Doesn't work either...??

**Comment by liayn** [comment]
`<html data-namespace-typo3-fluid="true" xmlns:f="https://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers">`
