### ISSUE TITLE
Provide a cleanup fonction for unused files and directories

### ISSUE THREAD

**Issue by gaumondp** [FriendsOfTYPO3/extension_builder#522]
**Is your feature request related to a problem? Please describe.**
The extension try to help us by providing many files and directories but it's possible those are unused and unmodified. 

**Describe the solution you'd like**
It would be nice™ to have the opportunity to cleanup the unused or unmodified files.

**Describe alternatives you've considered**
Maybe a diff based on a brand new extension generated by the extension and compared to the one we're working on but it's all manual work.

**Additional context**
The cleanup should be "bulletproof so nothing is lost. Maybe instead of deleting files move them to a directory outside the extension as a backup?

**Comment by simonschaufi** [comment]
The extension builder is smart enough already to only generate those files that you actually need. You can also disable a lot of things in the GUI already like "don't generate documentation". You can disable all the things that you don't need in the left sidebar.

Many people misunderstand the purpose of this extension. It is there to kickstart an extension and not to maintain it. I'm not willing to invest any time into this as it's not worth it. If you want to do that, please feel free to create a PR.

**Comment by gaumondp** [comment]
We know it's a "kickstarter extension".

We will provide a PR (I should have mentioned this in the original feature request which was more a "feature proposal").
