### ISSUE TITLE
Display the output directory and backup directory in the Extension Builder

### ISSUE THREAD

**Issue by alexander-nitsche** [FriendsOfTYPO3/extension_builder#533]
**Is your feature request related to a problem? Please describe.**
The output directory and the backup directory appear only occasionally in the Extension Builder.

**Describe the solution you'd like**
Since it is important information where your current extension is stored, it would be nice if both directory paths were permanently displayed in the Extension Builder graphical editor.

**Comment by PKuhlmay** [comment]
I am working on it in https://github.com/FriendsOfTYPO3/extension_builder/commit/e5835b7f8ec59bb64915febbd14ab7a191a20d45

I want to have some information inside the footer. The directories are a good candidate to be displayed there. Unfortunately, I don't have the information for the output directory yet. Only the backup directory is a true value at the moment.
This is not closed or finished, it is more WIP.

Screenshot of the footer information, including the directory paths.
<img width="1315" alt="Bildschirmfoto 2023-12-21 um 17 03 22" src="https://github.com/FriendsOfTYPO3/extension_builder/assets/107543296/55e245c8-e067-4a58-a61b-99fb9aef35a7">

**Comment by PKuhlmay** [comment]
Solved in https://github.com/FriendsOfTYPO3/extension_builder/commit/a8b54e493b096abe5c176046ffc087a6cd9767c6
