### ISSUE TITLE
How ExtensionBuilderConfigurationManager::getPersistenceTable is supposed to work?

### ISSUE THREAD

**Issue by vitalik1700** [FriendsOfTYPO3/extension_builder#548]
So, today I updated to extension_builder 10.0.2 on my Typo3 10.4.21 installation. And after trying to save my extension I got an error:
![image](https://user-images.githubusercontent.com/5510010/144485656-45867eb9-854b-4d0d-a0b2-14737454bdf2.png)

After checking extension files I found that problem is in function ExtensionBuilderConfigurationManager::getPersistenceTable
```
return GeneralUtility::makeInstance(DataMapper::class)->getDataMap($className)->getTableName();
```
There an instance of TYPO3\CMS\Extbase\Persistence\Generic\Mapper\DataMapper is created which indeed has 7 arguments.

Changing code to
```
    public function getPersistenceTable(string $className): string
    {
	$obj = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\Object\ObjectManager::class);
        return $obj->get(DataMapper::class)->getDataMap($className)->getTableName();
    }
```
seems to be fixing the issue. 

Maybe I'm missing something, but I don't see how above code (with makeInstance) can work at all.

I encounter this bug since I have a class with parent class set (standard fe_user being overriden)
![image](https://user-images.githubusercontent.com/5510010/144486697-716c8f8d-0752-401f-9563-5ce70017f8aa.png)

**Comment by simonschaufi** [comment]
It should work because of dependency injection, see https://github.com/FriendsOfTYPO3/extension_builder/blob/10.x/Configuration/Services.yaml#L18-L22

Can you please try to delete the DI cache (via install tool) and try it again? I can't reproduce your problem

**Comment by vitalik1700** [comment]
Okay, after some fiddling with cache the problem seems to have disappeared. Thanks for the feedback!
