### ISSUE TITLE
locallang.xlf merge does not work

### ISSUE THREAD

**Issue by Gernott** [FriendsOfTYPO3/extension_builder#565]
**Describe the bug**
When you add own labels into an xlf file and edit the extension with the extension_builder and save, the own labels are removed.
settings.yaml:
```
  Resources:
    Private:
      Language: merge
```

**To Reproduce**
1. Add one or more labels by hand to locallang.xlf in your extension
e.g.:
```
<trans-unit id="firstname" resname="firstname">
	<source>Firstname</source>
</trans-unit>
```
2. Set the Language folder to merge in your settings.yaml
3. Open your extension with the extension_builder again and save it
4. The own label is removed

**Expected behavior**
The own label should not be removed, as in earlier versions of the extension_builder.

**TYPO3 Version**
10.4.23

**Extension Builder Version:**
TER version 10.0.3

**Comment by davsalv** [comment]
I can confirm the same issue with 

**TYPO3 Version:**
11.5.13

**Extension Builder Version:**
TER version 11.0.3
