### ISSUE TITLE
PHP 8: Extension cannot be saved: overwriteSettings

### ISSUE THREAD

**Issue by franzholz** [FriendsOfTYPO3/extension_builder#577]
When I use TYPO3 11.5.7 and PHP 8.0.15 and I click to save a newly created extension, then this fails in a warning:

**Extension could not be saved: PHP Warning: Undefined array key "overwriteSettings" in /var/www/html/typo3conf/ext/extension_builder/Classes/Service/RoundTrip.php line 1024**

**Comment by franzholz** [comment]
If I fix the above error, then I get more errors.

**Extension could not be saved: PHP Warning: Undefined array key 500 in /var/www/html/typo3conf/ext/extension_builder/Classes/Controller/BuilderModuleController.php line 619**

**Comment by franzholz** [comment]
If I fix the above error, then it still fails.

**Extension could not be saved: Could not create directory "/var/www/html/var/tx_extensionbuilder/backups/"!**

**Comment by benwick** [comment]
These undefined array index warnings in PHP8 should be fixed fast. As it stands now, this extension is worthless in PHP8 environment...

**Comment by simonschaufi** [comment]
@franzholz the Bug #579 has nothing to do with PHP 8. Use composer and the error will be gone!

**Comment by simonschaufi** [comment]
@benwick would you please create a pull request and provide a fix? This project is not a one man show. Everybody can contribute! Unfortunately there is no budget from the association this year which means every contribution must be voluntary.

**Comment by franzholz** [comment]
This issue is fixed in version 11.0.3.
