### ISSUE TITLE
re:write extension in a pristine state

### ISSUE THREAD

**Issue by softstein** [FriendsOfTYPO3/extension_builder#596]
After running into a problem with my extension (CRUD functionality) I'd like to check if the problem existed in the first place.
(the problem is: on editAction validators complain about empty values of a related reference object; if I fix this editAction runs into a memory leak until timeout).
So I'd like to let write the extension with unmodified code to check if this behaviour existed in the first place (due to erroneous configuration in extBuilder).

In extension_builder for T3 v9.x it was possible to open the extension in extension_builder, then delete the extension folder and let it generate fresh unmodified files.

In T3 v10 this does not seem to be possible any more (the code is always merged with previous code).Re:commenting keep in settings.yaml doesn't help.

In this situation I'd find it helpful (at least to know how) to create the extension in a fresh state. Is there any way to do this in v10 ?

**Comment by softstein** [comment]
Seems deactivating round trip help (reading the manual, too :)

**Comment by simonschaufi** [comment]
The source of all generated files is the json file.

**Comment by softstein** [comment]
Herzlichen Dank für die Info Simon!
Sehr gut zu wissen :)

Und ja, mach ich künftig.

Liebe Grüße
Jan
