### ISSUE TITLE
Error while saving: Server responded with Status-Code: 0

### ISSUE THREAD

**Issue by webfacer** [FriendsOfTYPO3/extension_builder#6]
I got this error:
**Error while saving: 
Server responded with Status-Code: 0
Statustext: communication failure**
You can also see it on the image.

<img width="976" alt="extension_builder" src="https://cloud.githubusercontent.com/assets/137019/17476268/6b50adba-5d5f-11e6-9be7-74c04610ee53.png">

**Comment by manu09** [comment]
I also have the same error. I remember I already had this one and there is a solution on the web.

**Comment by webfacer** [comment]
thank you. okey when will you push it. it is for me now not necessary to change it manual. then i will close this issue.
