### ISSUE TITLE
Broken Relation-Editing since 11.0.4 (Javascript Errors)

### ISSUE THREAD

**Issue by Flimmerkiste** [FriendsOfTYPO3/extension_builder#623]
**Describe the bug**
The editing of relations in the Extension Builder is not working anymore since version 11.0.4 - presumably due to javascript errors.

**To Reproduce**
* **New Extension**
  1. Create new extension
  2. Create new Domain Object
  3. Click "Add" to add a new relation
  4. This yields a JS error in the console, preventing the user from actually adding a relation

* **Existing Extension**
  1. Open existing Extension that already contains relations in EB 
  2. This directly yields a JS error in the console. The overlay for selecting extensions doesn't close.
  3. When closing the overlay by hand, the existing relations are gone, together with the connected domain objects.

**Expected behavior**
Creating / Editing Relations should work as before. It worked up to version 11.0.3.

**Screenshots**
**JS-Error when creating new extension/relation**
![Bildschirmfoto 2022-10-10 um 08 48 05](https://user-images.githubusercontent.com/3634617/194813675-ef655f47-2aec-451c-bac9-06377daf4d09.png)

**JS-Error when opening existing extension** 
![Bildschirmfoto 2022-10-10 um 08 48 37](https://user-images.githubusercontent.com/3634617/194813711-06323d82-2912-41c8-8b6e-ab9cc5a257f6.png)

**TYPO3 Version**
11.5.16

**Extension Builder Version:**
11.0.4 - 11.0.7

**Comment by PKuhlmay** [comment]
Hi @Flimmerkiste can you please test the master-branch if it is working now? I had to revert a fix for another issue. The other fix caused this error.

**Comment by Flimmerkiste** [comment]
Hi @PKuhlmay, yes, when using `dev-master` the errors are now gone and the relation functionality works as expected for me 👍

**Comment by PKuhlmay** [comment]
@Flimmerkiste thanks for testing. I just released a new bugfix version.
