### ISSUE TITLE
Create new plugins with PLUGIN_TYPE_CONTENT_ELEMENT

### ISSUE THREAD

**Issue by bmack** [FriendsOfTYPO3/extension_builder#626]
**Is your feature request related to a problem? Please describe.**
As TYPO3 Core is moving towards more "flexible" Content Types, I think we should move extension builder as best practice to create plugins with a certain CType, instead of CType=list + list_type=plugin name.

This way, the hurdle for a lot of developers is reduced and Extbase feels more like a "Content element based on PHP code" type than this crude speciality.

**Describe the solution you'd like**
We need to adapt the extLocalconf.phpt file, and change the registration to `PLUGIN_TYPE_CONTENT_ELEMENT` - then also adapt the FlexForm registration and the new content element wizard, I don't think there is much else to do instead.

Thanks for consideration.

**Comment by DavidBruchmann** [comment]
That's a good idea I think.  
I want to mention that list_type still is useful, no matter if for a classic plugin or an own CType.  
I created an own CType using list_type. The CType characterizes a container element for b13/container and the list_type the type of the container. As container-types share the same basic cols a user can switch the type without need to adjust the position related to colPos or even dragging it from one container-element in another one.   
This scenario might sound special, but it's pretty straight forward and a logical consequence from using CType for more plugins.

**Comment by bmack** [comment]
@DavidBruchmann wow. very interesting use-case - you should blog about it.

Yes, I'm mainly talking about the complex list_type structure for "plugins" and "non-plugins" - the rest of it is still kept for the time being.

The main idea is just to reduce the brain-cell-usage for people wanting to create custom content types or plugins.

**Comment by DavidBruchmann** [comment]
@bmack I'd be happy to create an article as guest author for the B13 blog about it :)

**Comment by PKuhlmay** [comment]
Solved, this needs some testing.
Plugins are now their own CType. Each Plugin gets its own FlexForm, which only has one default input field and must be adjusted by the developer afterwards.
