### ISSUE TITLE
l10n_parent default SQL error

### ISSUE THREAD

**Issue by wernert** [FriendsOfTYPO3/extension_builder#63]
With an Extension build on typo3 7.6.18, 
extension builder from ter, ver: 7.6.18

On copy paste a record i got the error:
_SQL error: 'Incorrect integer value: '' for column 'l10n_parent' at row 1'_ 

Cause: missing default in TCE

Solution:
add 
`'default' => 0,`
to 
`'l10n_parent' => [`

**Comment by liayn** [comment]
The actual cause is a core bug here. It violates the strict mode of your SQL server and tries to insert a string where integer is required. So adding the default is okay, but actually just a workaround.
Please make a pull request.

**Comment by wernert** [comment]
Hallo, for the pull request:
I have forked and cloned the projekt
inserted the default  in phpt template

Now i need a little help: 
do i have to and if > how to setup the unit tests ?

my core sources are installed via git + symlink
  i have also symlinked the vendor folder
core tests are running

on: 
```
vendor/phpunit/phpunit/phpunit -c vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml typo3conf/ext/extension_builder/Tests
vendor/phpunit/phpunit/phpunit -c vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml typo3conf/ext/extension_builder/Tests/Unit
```
i get a lot of errors cause: mockups,fixture.. not found

so i assume there is another build/install/setup step ?

**Comment by nicodh** [comment]
The second line should work if you have set the Environment variables and the composer install (like the steps you can see in the travis.yml)

For the change you made there is no need to add a unit test but you probably have to adapt the files in Tests/Fixtures/TestExtensions/test_extension as these are the references to compare a generated extension (is peformed in Tests/Functional/CompatibilityTest). So the files in the fixtures should have the same changes as the configuration files generated with your patch...

**Comment by liayn** [comment]
@wernert Would you mind pushing your PR without unittests, so we can take a look?

**Comment by liayn** [comment]
Checked this against the Core itself. Most tables in Core indeed define the default as proposed.
