### ISSUE TITLE
Domain Modelling doesn't show anything

### ISSUE THREAD

**Issue by philippbarnickel** [FriendsOfTYPO3/extension_builder#64]
I installed the extension builder in the backend. Introduction is visible but in domain modelling is nothing like on the image. Are there wrong references to files and data?

![1](https://user-images.githubusercontent.com/22031386/27853562-75762faa-6163-11e7-9580-2805b035847e.PNG)

**Comment by philippbarnickel** [comment]
TYPO3 [7.6.18] is running on XAMPP (Apache/2.4.25 (Win32), OpenSSL/1.0.2j, PHP/7.1.6)

**Comment by nicodh** [comment]
It might be an URL issue. What is your typo3 backend path?
Can you try to apply ab5485364

**Comment by philippbarnickel** [comment]
I'm using TYPO3 on a local Apache-Webserver on XAMPP. Therefore my Backend-Path is 'localhost/typo3'

**Comment by nicodh** [comment]
Do you see any errors in Javascript console or network console?

**Comment by philippbarnickel** [comment]
Hi nicodh, I'm so sorry to answer so late. The extension works now - don't know why :D 
Best regards phil
