### ISSUE TITLE
[TYPO3 12] Buttons 'new', 'save' etc. not working

### ISSUE THREAD

**Issue by ste101** [FriendsOfTYPO3/extension_builder#656]
When clicking on the buttons then I'm getting no reaction
![grafik](https://github.com/FriendsOfTYPO3/extension_builder/assets/359959/72ac4c3d-e9b8-4bcd-8b8d-f73f469fb7ba)

I can see JS error at the browser console:
Uncaught ReferenceError: inputEx is not defined
Uncaught (in promise) ReferenceError: YAHOO is not defined

If enforceContentSecurityPolicy for the backend ist active there is also an error.

TYPO3 12.4.2
PHP 8.2

**Comment by PKuhlmay** [comment]
There is no release for v12 yet. The UI will be rewritten and Yahoo UI will not be removed. So I close this issue.
