### ISSUE TITLE
Branch typo3-12-reactjs: PHP Runtime Deprecation Notice

### ISSUE THREAD

**Issue by fritzdacat** [FriendsOfTYPO3/extension_builder#661]
I have installed the branch "typo3-12-reactjs". Now I am getting this error:

(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Runtime Deprecation Notice: Creation of dynamic property EBT\ExtensionBuilder\Controller\BuilderModuleController::$fileGenerator is deprecated in /var/www/html/vendor/friendsoftypo3/extension-builder/Classes/Controller/BuilderModuleController.php line 66

TYPO3: 12.4.7
PHP: 8.2.9

**Comment by PKuhlmay** [comment]
Hi @fritzdacat Thank you for testing and reporting this issue.
When do you get this issue? Just after installation? 

I'll have a look at it.

**Comment by fritzdacat** [comment]
After the installation and clicking on "Extension Builder"

**Comment by PKuhlmay** [comment]
This only happens, if TYPO3 is in debug mode:
<img width="1146" alt="Bildschirmfoto 2023-11-04 um 15 46 29" src="https://github.com/FriendsOfTYPO3/extension_builder/assets/107543296/aa363ac2-8ea5-4293-b1c7-2dd96bd11b31">

**Comment by fritzdacat** [comment]
Okay, thanks. When I'm developing, I'm usually in "debug mode". But at least that way I can test.

**Comment by PKuhlmay** [comment]
This should be fixed now in the TYPO3 12 branch. Can you please test this?

**Comment by PKuhlmay** [comment]
I close this for now as it is fixed. If this happens again, please reopen this issue.
