### ISSUE TITLE
🐛 [BUG] Dynamic property $default in NodeFactory.php is deprecated

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/extension_builder#662]
Could not generate domain model, error: PHP Runtime Deprecation Notice: Creation of dynamic property PhpParser\\Node\\Stmt\\Property::$default is deprecated in /var/www/html/Packages/extension_builder/Classes/Parser/NodeFactory.php line 237

PHP 8.2 only, PHP 8.1 works.
TYPO3 12
EB: v12.0.0-alpha.1

**Comment by Starraider** [comment]
Problem still exists in EB v12.0.0-alpha.6
PHP 8.2.13
TYPO3 12.4.10

**Comment by PKuhlmay** [comment]
See #685
