### ISSUE TITLE
PHP Warning: Undefined array key "ignoreWarnings"

### ISSUE THREAD

**Issue by ste101** [FriendsOfTYPO3/extension_builder#664]
After clicking the save button this warning occurs:
`... Something went wrong on server side{"error":"PHP Warning: Undefined array key \"ignoreWarnings\" in /var/www/vhosts/hosting186280.ae8cd.netcup.net/coolingcure.de/httpdocs/coolingcure.de/typo3conf/ext/extension_builder/Classes/Controller/BuilderModuleController.php line 520"}`

![grafik](https://github.com/FriendsOfTYPO3/extension_builder/assets/359959/1bf6602d-bc05-4cf6-b5dd-136e082bb51f)

12.4.7

Latest Git-branch non composer

**Comment by PKuhlmay** [comment]
Fixed in v12.0.0-alpha.1
