### ISSUE TITLE
🐛 [BUG] Only one PlugIn can be created v12.0.0-alpha.1

### ISSUE THREAD

**Issue by webschuppenuser** [FriendsOfTYPO3/extension_builder#666]
**Describe the bug**
I cannot create multiple PlugIns, because the form field values of the first PlugIns get overwritten by the most current PlugIn form field values.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on 'add new plugin'
2. Enter PlugIn Name, Key, Controller/Action
3. Click on 'add new plugin'
4. Enter PlugIn Name, Key, Controller/Action
5. Then look at the first created PlugIn, the values get overwritten by the values added in the second one

**Expected behavior**
Expected that I can create multiple PlugIns without them influence one another

**Screenshots**
![Screenshot 2023-11-24 at 08 44 06](https://github.com/FriendsOfTYPO3/extension_builder/assets/20123497/ab955094-455a-44a2-8180-83e193ce0412)

**TYPO3 Version**
12.4.7 (composer mode)

**Extension Builder Version:**
v12.0.0-alpha.1

**Comment by PKuhlmay** [comment]
Same for modules and authors

**Comment by PKuhlmay** [comment]
Should be fixed in https://github.com/FriendsOfTYPO3/extension_builder/commit/d7e51046f17467355b70319d1cbb4e0b812cf03b but needs some more testing.
