### ISSUE TITLE
I have installed 12.0.0-alpha.1 , but I can not open or create a newproject!

### ISSUE THREAD

**Issue by hgalt** [FriendsOfTYPO3/extension_builder#667]
**Describe the bug**
I am to early or do I something wrong?

**Comment by PKuhlmay** [comment]
Hi @hgalt is it now solved? You closed this issue? Maybe you had the Content Security Policy active? It is not working at the moment when this is active. I already created an issue today.

It is still in alpha and I need people like you to test it and to find all the bugs. Thanks.

**Comment by PKuhlmay** [comment]
@hgalt This might be the issue with the content security policy enabled. Then the scripts are not loading. When you deactivate them in the features, then it should work. I know that this isn't the correct solution but I am working on it. The goal is, that it is still working when the CSP is enabled.

The buttons are only a placeholder at the moment. I think I will remove them later. 

There is already an issue for this: #669

**Comment by hgalt** [comment]
Ok I have downloaded it and I cann see now on the left side the menu.
But it is still shown as alpha.1. I guess you mabe forgot to up date it.
There are new Inputs. I would see it at useful, if a help text would be displayed, if I go with the mouse over the name. For example category.
I will test it and give you a feedback.

**Comment by hgalt** [comment]
I have created a first Ext. Now when I press Open, I get a window which says 
Fetching failed. 
Fetching the extensions failed. Please check, if you have extensions with a valid extensionbuilder.json file.

**Comment by PKuhlmay** [comment]
Hi yes indeed I forgot to update the version inside the ext_emconf. 

I need to test it, why you get the error message of "fetching the extensions failed ......". I will create a new issue for that and close this one.
I will create a new issue for the mouse over as well. 
For your information: I didn't create any new inputs. These are the same as in the "old" Extension Builder for TYPO3 11. At the moment, all input fields are shown as before. In Version 11 you had to open the "More options" to see all input fields.
