### ISSUE TITLE
🚧 Consider, making the font size a little bit bigger

### ISSUE THREAD

**Issue by PKuhlmay** [FriendsOfTYPO3/extension_builder#670]
The font size might be a little bit too small. 

TYPO3 12

**Comment by DavidBruchmann** [comment]
loosing slowly quality of the eyes, I can say the good contrast is important too

**Comment by PKuhlmay** [comment]
font size is increased inside https://github.com/FriendsOfTYPO3/extension_builder/commit/237a08fccf9e16881abd7699ac52322b478ca88c
