### ISSUE TITLE
Move makeCategorizable call to overrides

### ISSUE THREAD

**Issue by georgringer** [FriendsOfTYPO3/extension_builder#68]
The call to `\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::makeCategorizable` must be placed in Overrides/TCA/<tablename>.php instead of ext_tables.php

**Comment by tmotyl** [comment]
according to the documentation https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Categories/Index.html the folder should be:
` Configuration/TCA/Override/...php`

**Comment by georgringer** [comment]
yeah of course ^^;)
