### ISSUE TITLE
New Button missing

### ISSUE THREAD

**Issue by hgalt** [FriendsOfTYPO3/extension_builder#693]
Addition to Save and Open a new Button schould be added. Otherwise Extension Builder has to restarted.

**Comment by PKuhlmay** [comment]
I added a button in https://github.com/FriendsOfTYPO3/extension_builder/commit/87651a42a10a331dfc5e7bdee555a5f834ff5dfe
After hitting "new", an alert is shown. After clicking OK, the page is reloaded.
This is still WIP.

**Comment by PKuhlmay** [comment]
I close this for now as the button is already working. I didn't find a better solution for now.
