### ISSUE TITLE
Plugin declaration wrong

### ISSUE THREAD

**Issue by Gernott** [FriendsOfTYPO3/extension_builder#71]
If you add a frontend plugin, then the icon and text is missing on creating a new contentelement/plugin.

![bildschirmfoto vom 2017-07-27 13-38-41](https://user-images.githubusercontent.com/1930849/28668612-f55692ae-72d0-11e7-90e1-6f7bcaa1b67a.png)

**Comment by floriankuehl** [comment]
Check your ext_localconf.php.
The labels are defined in the locallang.xlf

**Comment by Gernott** [comment]
Thank you, that is correct. But the Label and the Description are missing in the locallang_db.xlf. If I add them by hand it works. I think this should be written by the extension_builder, or not?

The image does still not work. It exists in the given folder in the given filename. All seems to be right. In compare with EXT:news, it uses an icon class. Perhaps this is the only way in TYPO3 8.7?

**Comment by Gernott** [comment]
BTW: This is deprecated:
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extRelPath

**Comment by liayn** [comment]
Icons should be registered via API and should be referenced by identifier. I guess that needs some extra work to have all those icons generated correctly in ext_localconf
