### ISSUE TITLE
Icon-Paths are wrong ...

### ISSUE THREAD

**Issue by DavidBruchmann** [FriendsOfTYPO3/extension_builder#72]
... if TYPO3 is running in a sub-directory.
Paths are always prepended with "/" and the links show then to a wrong location.
Tested in branch 7.6, don't know yet about upper branches.

**Comment by liayn** [comment]
Are you referring to icons of extension builder itself or to those generated by it for new extensions?

**Comment by DavidBruchmann** [comment]
It's about the new extension.

**Comment by liayn** [comment]
As always for a good bug report, please add:

- Expected behaviour
- Actual behaviour

What does the generated URL look like, what should it look like, how to reproduce the fastest way? ;-)
Thanks.

**Comment by nicodh** [comment]
Should be fixed with current master. Can you please check again?
