### ISSUE TITLE
model view doesn't show anything when extension is loaded

### ISSUE THREAD

**Issue by DavidBruchmann** [FriendsOfTYPO3/extension_builder#720]
**Describe the bug**
Loading an extension in the builder shows all properties in the sidebar (name, key, author, etc.) but the models aren't loaded in the canvas area. The markup (html and svg) seems being existing though in the source.

**To Reproduce**
1. Create a simple extension, save it
2. Click on something else, like log-module or list-module
3. Go back to the extension builder and load the created extension
4. See missing models in canvas area.

**TYPO3 Version**
12.4

**Extension Builder Version:**
12.alpha.6

**Comment by PKuhlmay** [comment]
Hi @DavidBruchmann Could you provide the extensionbuilder.json file for me, so I can test this out? Maybe the models are just out of the view? You can zoom in and out and there is a small minimap.

**Comment by PKuhlmay** [comment]
I can't reproduce this at the moment. For me, it works inside the 12.alpha.6. It is still not possible to load older extensions, but in this issue you mean the extension, which you already created with version 12, right?

**Comment by DavidBruchmann** [comment]
Yes, I created it exactly in the same installation.

**Comment by DavidBruchmann** [comment]
Yes, I created it exactly in the same installation.

Actually it's working, I had to enlarge a lot, as the two models I created have been hardly visible in the minimap.
So I close for now, I think the zoom level would be another issue.

**Comment by PKuhlmay** [comment]
I will create another issue for this. I can customize it a little bit. I think I can increase the zoom level. I will have a look.

**Comment by DavidBruchmann** [comment]
@PKuhlmay  It might be useful, just to save the position and zoom, and open with the last known parameters.

**Comment by PKuhlmay** [comment]
@DavidBruchmann this would be the best solution but I have to figure out if this is possible with the “react flow”, which I am using.
