### ISSUE TITLE
Error when trying to save extension related to a dynamic property creation not allowed with PHP v8.2

### ISSUE THREAD

**Issue by Oktopuce** [FriendsOfTYPO3/extension_builder#721]
**Describe the bug**
Can't save extension with model with PHP v8.2.

1. Create an extension with extension builder
2. Add a model (it could be empty)
3. Click on the save icon
4. See error : 

> Extension could not be saved: Could not generate domain model, error: PHP Runtime Deprecation Notice: Creation of dynamic property PhpParser\Node\Stmt\Property::$default is deprecated in typo3conf/ext/extension_builder/Classes/Parser/NodeFactory.php line 237

**Expected behavior**
Can save the extension.

**TYPO3 Version**
11.5.34

**Extension Builder Version:**
11.0.11

**Additional context**
The problem is in method **NodeFactory::buildPropertyNode()** because a value is assigned to a non-existent property (i.e. **default**) of class **PhpParser\Node\Stmt\Property**:
 
`$propertyNode->default = $property->getDefault();`

**Comment by Starraider** [comment]
Same Problem also exists in TYPO3 12.4.10
PHP 8.2.13
EB v12.0.0-alpha.6

**Comment by PKuhlmay** [comment]
Solved in https://github.com/FriendsOfTYPO3/extension_builder/commit/02fed7796afa45952b3ae71e35d3689546ad76bf
See #685
