### ISSUE TITLE
Push tags and add a release for TYPO3 8.7

### ISSUE THREAD

**Issue by pixelbrackets** [FriendsOfTYPO3/extension_builder#74]
Hey Hey :)

could you do me a favour and please add a Git Tag for each release and push it to GitHub? 

Right now, when I use Composer, this extension may only be added with a "dev-master" version constraint. I would like to add specific versions however, to keep this extension working in different TYPO3 versions & setups.

When you do this, could you release a version for TYPO3 8 as well? The last relase in TER was 7.6.18 for TYPO3 7, on GitHub TYPO3 8 is supported but requires using "dev-master".

**Comment by ribase** [comment]
+1

**Comment by nicodh** [comment]
Done
