### ISSUE TITLE
Deprecations: ext_emconf.php

### ISSUE THREAD

**Issue by SSFGizmo** [FriendsOfTYPO3/extension_builder#746]
* https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ExtensionArchitecture/FileStructure/ExtEmconf.html

**clearCacheOnLoad** can be removed

OLD
```
/Resources/Private/CodeTemplates/Extbase/extEmconf.phpt

    'state' => '{extension.readableState}',
    'clearCacheOnLoad' => 0,
    'version' => '{extension.version}',
```

NEW

```
    'state' => '{extension.readableState}',
    'version' => '{extension.version}',
```

**TYPO3 Version**
v12.4

**Extension Builder Version:**
v12.0.0-beta.2

**Comment by PKuhlmay** [comment]
fixed by #747
