### ISSUE TITLE
Show another message when no extensions to open are available

### ISSUE THREAD

**Issue by DavidBruchmann** [FriendsOfTYPO3/extension_builder#768]
**Is your feature request related to a problem? Please describe.**
Without available extensions to edit an advice is shown to select an extension from a non-existing list.

![image](https://github.com/FriendsOfTYPO3/extension_builder/assets/999146/9b6e312c-e94e-4e7e-925c-1c51adda2e75)

**Describe the solution you'd like**
Another message should be shown.

**Describe alternatives you've considered**
The whole button to open this dialog could be disabled too, but that might confuse users, especially if an extension is expected to be listed.

**Comment by PKuhlmay** [comment]
Fixed via https://github.com/FriendsOfTYPO3/extension_builder/commit/62ad2ced106266d1adaf2c02f832fc3bd376aa13
