### ISSUE TITLE
Suddenly Error Non-static method EBT\ExtensionBuilder\Parser\NodeFactory::buildNodeFromValue()

### ISSUE THREAD

**Issue by robsonrobi** [FriendsOfTYPO3/extension_builder#86]
Hi. Working with TYPO3 8.7.4 with the dev-master of the extensionbuilder, that error appeared suddenly?

`
Extension could not be saved: Could not generate action controller, error: PHP Runtime Deprecation Notice: Non-static method EBT\ExtensionBuilder\Parser\NodeFactory::buildNodeFromValue() should not be called statically in /app/htdocs/typo3conf/ext/extension_builder/Classes/Parser/NodeFactory.php 
`

An idea?

**Comment by liayn** [comment]
Check if the patch works for you pls

**Comment by liayn** [comment]
@robsonrobi ping. Does the proposed fix solve the issue for you?
