### ISSUE TITLE
Backend Module without CSS/JS in iframe

### ISSUE THREAD

**Issue by mcmulman** [FriendsOfTYPO3/extension_builder#88]
Version: 8.7.0
TYPO3: 8.7.3

I build a backend module and the form output is correct.
But the included content within the iframe is no standard html page.
There is no html-tag, no head and no body.

The main problem: all of the default css/js includes are missing, and so the styling of the backend forms is impossible.

Can you please give me a hint?

Thanks
mcmulman

**Comment by liayn** [comment]
Maybe compare your BE module with those used in the Core. I guess you overlooked some detail.

**Comment by mcmulman** [comment]
But that's what the extension_builder generates for me.
I added a model with some forms and enabled the option "backend module".

Do I have to add something manually to get a correct backend form?
In my tests doing this with extension_builder I always get a incomplete html page within the iframe where the backend modules are shown normally.

**Comment by nicodh** [comment]
Do you see any network error in console? Is your typo3 backend in a subdirectory?
Please try to debug and tell us what you found...

**Comment by mcmulman** [comment]
It's no subdirectory and there's no error in console.
It just loads the modul without proper html frame into the second column.
The loaded html starts with 
<div class="tx-myext">...</div>

**Comment by mcmulman** [comment]
Moving the generated templates from _Resources/Private/Backend/..._ to _Resources/Private/..._ solved the problem.
As I added a frontend plugin and also a backend modul (via builder extension), there have already been templates within _Resources/Private/..._. But they probably didn't contain the correct wrapper to generate a backend module.

So it seems that the templates for backend modules are not correct included out of _Resources/Private/Backend/..._ or what do you think?

Thanks for your help.
Mathias

**Comment by nicodh** [comment]
I could reproduce it. It's obviously a bug.
Thanks for reporting.

**Comment by nicodh** [comment]
Ok I found that this is related to a TYPO3 core bug:
https://forge.typo3.org/issues/82181
If I checkout the last commit before 6e02927806 it works as expected

**Comment by mcmulman** [comment]
Great, thanks for helping.
So finally I was searching at the wrong place...
