### ISSUE TITLE
Can't save after adding a frontend plugin

### ISSUE THREAD

**Issue by ste101** [FriendsOfTYPO3/extension_builder#89]
With latest master I'm getting an error 'template not found' after adding a frontend plugin:
![extension_builder_error](https://user-images.githubusercontent.com/359959/30521255-263cc4e6-9bbd-11e7-8108-dd9c132d7124.png)
I can fix this by reverting this patch in file Classes/Service/FileGenerator.php introduced in task 65 https://github.com/FriendsOfTYPO3/extension_builder/pull/82/commits/62b6c591c7dd7fb3ae0d2f6e248136de20ffa786
```
@@ -366,7 +375,7 @@
                  * @var \EBT\ExtensionBuilder\Domain\Model\DomainObject\Action $action
                  */
                 if ($action->getNeedsTemplate()
-                    && file_exists($this->codeTemplateRootPath . $templateRootFolder . 'Templates/' . $action->getName() . '.htmlt')
+                    && file_exists($this->getTemplatePath($templateRootFolder . 'Templates/' . $action->getName() . '.htmlt'))
```

**Comment by nicodh** [comment]
@ste101 can you please have a look at your Typoscript?
Maybe it didn't get updated: it should have a setting:
`module.extension_builder.settings.codeTemplateRootPaths.0 = EXT:extension_builder/Resources/Private/CodeTemplates/Extbase/`

**Comment by ste101** [comment]
The path is correct:
![extension_builder_error1](https://user-images.githubusercontent.com/359959/30521920-3000391c-9bc8-11e7-9851-86a853760063.png)

**Comment by nicodh** [comment]
Ok, found it: The method \EBT\ExtensionBuilder\Service\FileGenerator::getTemplatePath should not throw an Exception if a template for a custom action is not found, since these have no templates of course...

**Comment by ste101** [comment]
Thank you very much
