### ISSUE TITLE
Add 'l10n_mode' to 'show advanced options'

### ISSUE THREAD

**Issue by ste101** [FriendsOfTYPO3/extension_builder#90]
It would be great if the 'l10n_mode' would be selectable after activating 'show advanced options' like 'is required' and 'is exclude field'.
![extension_builder_l10n_mode](https://user-images.githubusercontent.com/359959/30522418-e464a3fa-9bcf-11e7-9e72-7f321be5b138.png)

**Comment by ste101** [comment]
I made a patch:
[extension_builder_l10n.txt](https://github.com/FriendsOfTYPO3/extension_builder/files/1320945/extension_builder_l10n.txt)
Maybe you can take a look at it. If the patch is ok I will make a pull request.

**Comment by liayn** [comment]
@ste101  Please push your proposed change as pull request right away. That's what PRs are there for. Reviewing is much more convenient here and we can post comments on your change proposal too. Thanks.

**Comment by nicodh** [comment]
Implemented with commit  8a0115b75b5abffef1fff7c10efb0699d5c0bd4d
