### ISSUE TITLE
Deprecation-Warnings related to "enableClickMenu"

### ISSUE THREAD

**Issue by p1ngb4ck** [FriendsOfTYPO3/extension_builder#95]
Hi =)
I get those deprecation-warnings :
19.09.2017 16:24: [typo3conf/ext/extension_builder/Resources/Private/Templates/BuilderModule/Domainmodelling.html] The property "enableClickMenu" has been marked as deprecated. Setting "enableClickMenu" in Container ViewHelper is deprecated, the option will be removed in TYPO3 v9 Please check also your partial and layout files of this template
Can anybody fix those, please? thanks in advance

**Comment by nicodh** [comment]
Hmm I don't see that property in that file:
https://github.com/FriendsOfTYPO3/extension_builder/blob/master/Resources/Private/Templates/BuilderModule/Domainmodelling.html
We only use <f:be.menus.actionMenu>

**Comment by p1ngb4ck** [comment]
me neither. That`s why I filed an issue, couldn`t find the source of that error myself.. I use current git version..

**Comment by liayn** [comment]
I suspect some indirect usage here. The option `enableClickMenu` defaults to `true`, hence unless you set it to false, you will always see this deprecation notice.

**Comment by liayn** [comment]
@p1ngb4ck How to reproduce this? Can you please post a minium setup? Thanks

**Comment by p1ngb4ck** [comment]
Easy to reproduce : Simply enable deprecation-logs (Installation->All Configuration->Sys) and open up Extension-Builder-Module. I suspect some indirect usage due to the usage of the action-menu or the ViewHelper, but actually I don`t know, I have been unable to find the source of it myself yet.
I use current git version from here.

**Comment by p1ngb4ck** [comment]
Ok I found it now. You were right : the ViewHelper implements AbstractBackendViewHelper etc. which includes enableClickMenu as Argument, defaulting to true. Unfortunately, overriding (via $this->overrideArgument in the configuration-viewhelper and setting this to false results in broken module...

**Comment by p1ngb4ck** [comment]
Issue can be closed. Issue is based on ContainerViewHelper-Function initializeArguments() in the typo3-src which has been updated in latest git version.
