### ISSUE TITLE
Rendertype for 1:n relations has no effect

### ISSUE THREAD

**Issue by JarvisH** [FriendsOfTYPO3/extension_builder#98]
When setting relations for a model object to 1:n, the renderType dropdown has no effect, as the template used to generate the relevant TCA code has renderType "inline" hardcoded. The template used is `CodeTemplates/Extbase/Partials/TCA/ZeroToManyRelation.phpt`

![rendertype](https://user-images.githubusercontent.com/1301804/30694643-28b57ebe-9ed5-11e7-950a-ed898d4921e1.png)

**Comment by nicodh** [comment]
Hmm, the dropdown doesn't make sense at all for a 1:n relation, since you can't select multiple items in a dropdown. But we should offer selectCheckbox  or multi select...

**Comment by nicodh** [comment]
It seems at the moment 1:n relations can only be implemented with IRRE
see: https://forge.typo3.org/issues/82549
